### ISSUE TITLE
netmap should be version agnostic

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#106]
Problem arises when Tcpreplay is compiled on one machine then run on another. This is controlled by the "NETMAP_API" parameter, which is currently at version 11. If you compile Tcpreplay on version 11, it will not run on a machine that has a version 10 netmap driver installed.

This also happens with FreeBSD. FreeBSD 8.4 have it's NETMAP_API set to 0. FreeBSD 10 has NETMAP_API set to 4.

Tcpreplay should handle all netmap driver versions regardless of the version that it was compiled on.

**Comment by smolrise** [comment]
> Hello Fred. I tried 'sudo make test' to test tcpreplay on freeBSD 11.0 and there is no error.
> And I tried to generate traffic with tcpreplay+netmap on ubuntu 12.04. This time, another problem occurs.
> I just download the tcpreplay-4.04 package. configure, make and make test. Then there is test error as follows.
> 
> [tcpreplay] Basic test: make[1]: *** [replay_basic] Error 255
> [tcpreplay] Cache test: make[1]: *** [replay_cache] Error 255
> [tcpreplay] Packets/sec test: make[1]: *** [replay_pps] Error 255
> [tcpreplay] Mbps test: make[1]: *** [replay_rate] Error 255
> [tcpreplay] Topspeed test: make[1]: *** [replay_top] Error 255
> [tcpreplay] Config file/VLAN add test: make[1]: *** [replay_config] Error 255
> [tcpreplay] Multiplier test: make[1]: *** [replay_multi] Error 255
> [tcpreplay] Packets/sec Multiplier test: make[1]: *** [replay_pps_multi] Error 255
> [tcpreplay] Precache test: make[1]: *** [replay_precache] Error 255
> [tcpreplay] Statistics test: make[1]: *** [replay_stats] Error 255
> [tcpreplay] Dual file test: make[1]: *** [replay_dualfile] Error 255
> [tcpreplay] Maximum sleep test: make[1]: *** [replay_maxsleep] Error 255
> 
> My tcpreplay version info:
> tcpreplay version: 4.0.4 (build git:v4.0.4)
> Copyright 2013-2014 by Fred Klassen - AppNeta Inc.
> Copyright 2000-2012 by Aaron Turner
> The entire Tcpreplay Suite is licensed under the GPLv3
> Cache file supported: 04
> Not compiled with libdnet.
> Compiled against libpcap: 1.1.1
> 64 bit packet counters: enabled
> Verbose printing via tcpdump: enabled
> Packet editing: disabled
> Fragroute engine: disabled
> Default injection method: PF_PACKET send()
> Optional injection method: netmap
> 
> I tried to send packets. This time tcpreplay can send packets successfully but the speed is limited to about 85Mbps. I fulfilled the process according to your teaching video on youtube.
> 
> $ lsmod
> Module Size Used by
> ixgbe 178778 0
> netmap_lin 205437 1 ixgbe
> xt_LOG 17280 2
> xt_statistic 12537 10004
> iptable_filter 12706 1
> ip_tables 18106 1 iptable_filter
> ...
> 
> $ sudo tcpreplay -i eth4 --mbps=1000 --netmap exp_TCP_eth4.pcap
> Switching network driver for eth4 to netmap bypass mode... done!
> Warning: exp_TCP_eth4.pcap was captured using a snaplen of 32767 bytes. This may mean you have truncated packets.
> Actual: 42748 packets (63780016 bytes) sent in 6.02 seconds.
> Rated: 10190560.2 Bps, 81.52 Mbps, 6830.13 pps
> Flows: 42748 flows, 6830.13 fps, 42748 flow packets, 0 non-flow
> Statistics for network device: eth4
> Attempted packets: 42748
> Successful packets: 42748
> Failed packets: 0
> Truncated packets: 0
> Retried packets (ENOBUFS): 0
> Retried packets (EAGAIN): 0
> Switching network driver for eth4 to normal mode... done!
> 
> I wonder why the speed is limited.
> Thanks, Fred

Hello yaoyj11 I stumbled upon the same problems with errors within the result of testing. But after switching to debug mode, I found that test script set a standard name for the interface - "eth0", which is absent on my OS. So, to fix this problem it is just necessary to go to the directory <tcpreplay location>/test and change the interface name for the interface in the files "Makefile" and "config". After this, all tests pass successfully!
BR, Sergey
