### ISSUE TITLE
Extra packets sent with "-L" option

### ISSUE THREAD

**Issue by morphyno** [appneta/tcpreplay#173]
I'm always noticing an "extra" packet sent when using the "-L" option. Also, this packet is always an malform packet. 

sudo /usr/local/bin/tcpreplay --netmap -i eth6 -L 1000 -tK rx_stc_sig.pcap
Switching network driver for eth6 to netmap bypass mode... done!
File Cache is enabled
Actual: 1001 packets (60060 bytes) sent in 0.000449 seconds.
Rated: 133763919.8 Bps, 1070.11 Mbps, 2229398.66 pps
Flows: 1 flows, 2227.17 fps, 1000000 flow packets, 0 non-flow
Statistics for network device: eth6
        Attempted packets:         1001
        Successful packets:        1001
        Failed packets:            0
        Truncated packets:         0
        Retried packets (ENOBUFS): 0
        Retried packets (EAGAIN):  0
Switching network driver for eth6 to normal mode... done!

I'm seeing this with and without netmap 

sudo /usr/local/bin/tcpreplay -i eth6 -L 1000 -tK rx_stc_sig.pcap
File Cache is enabled
Actual: 1001 packets (60060 bytes) sent in 0.001041 seconds.
Rated: 57694524.4 Bps, 461.55 Mbps, 961575.40 pps
Flows: 1 flows, 960.61 fps, 1000000 flow packets, 0 non-flow
Statistics for network device: eth6
        Attempted packets:         1001
        Successful packets:        1001
        Failed packets:            0
        Truncated packets:         0
        Retried packets (ENOBUFS): 0
        Retried packets (EAGAIN):  0

This is what that packet looks like on wireshark 

![malformed](https://cloud.githubusercontent.com/assets/3343500/5842966/f33b79cc-a15d-11e4-8d97-d3839195cb5b.png)

This is not a big deal or anything, but i'm actually generating Spirent Testcenter signatures from ixgbe (as a source to testcenter) and its confusing Testcenter

**Comment by fklassen** [comment]
Thanks for reporting. I hope to schedule shortly.

**Comment by fklassen** [comment]
Seems to be working now due to lots of bug fixes. Thanks for reporting.

```
fklassen@debian-fred:~/git/tcpreplay$ sudo src/tcpreplay -i eth0 -Kt -L 1000 -l 10 v6.pcap 
File Cache is enabled
Actual: 1000 packets (159984 bytes) sent in 0.603071 seconds.
Rated: 265200.0 Bps, 2.12 Mbps, 1658.17 pps
Statistics for network device: eth0
	Attempted packets:         1000
	Successful packets:        1000
	Failed packets:            0
	Truncated packets:         0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0
fklassen@debian-fred:~/git/tcpreplay$ sudo src/tcpreplay -i eth0 -Kt -L 100  v6.pcap 
File Cache is enabled
Actual: 100 packets (16200 bytes) sent in 0.000490 seconds.
Rated: 33061200.0 Bps, 264.48 Mbps, 204081.63 pps
Statistics for network device: eth0
	Attempted packets:         100
	Successful packets:        100
	Failed packets:            0
	Truncated packets:         0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0
fklassen@debian-fred:~/git/tcpreplay$ sudo src/tcpreplay -i eth0 -Kt -L 1000  v6.pcap 
File Cache is enabled
Actual: 161 packets (25651 bytes) sent in 0.001311 seconds.
Rated: 19565900.0 Bps, 156.52 Mbps, 122807.01 pps
Statistics for network device: eth0
	Attempted packets:         161
	Successful packets:        161
	Failed packets:            0
	Truncated packets:         0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0
```
