### ISSUE TITLE
Cannot compile netmap

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#177]
From direct email to me ...

I saw your video of building netmap, but have failed to produce any working build due to rejected patches or other problems.
Are you aware of any instructions for building netmap that actually work with the latest netmap code and latest CentOS or Ubuntu version?
I did see a comment that you had used Ubuntu 14 for your video, is this correct?  I see a “3.1.10” directory name in the video, so I’m assuming that is the kernel version…?
All I find on the net is others struggling with similar issues and your video makes it look so easy…I’m willing to backdate to a specific version if that is required.
Thanks

**Comment by fklassen** [comment]
The trick with compiling NetMap is that it requires the entire kernel source, not just kernel headers. So, this will not work:
```
$ ll /lib/modules/`uname -r`/
total 3684
lrwxrwxrwx  1 root root     37 Feb  3 17:03 build -> /usr/src/linux-headers-3.16.0-4-amd64
...
```

The following does work because I am referencing the source code for the running kernel (in my case Linux version 3.10.33):
```
$ ll /lib/modules/`uname -r`
total 708
drwxr-xr-x 6 root root   4096 2015-03-21 09:47 ./
drwxr-xr-x 7 root root   4096 2015-02-02 10:18 ../
lrwxrwxrwx 1 root root     78 2014-09-24 21:30 build -> /home/fklassen/git/pvc-appliance/Appliances/Common64/Kernel-3.10/linux-3.10.33/
```

**Comment by eapster123** [comment]
Hi
I did finally get everything compiled everything successfully after moving from CentOS 7 to Ubuntu 14.04.2 LTS
But now I can't get tcpreplay run in a reliable fashion:

tcpreplay --netmap -t -i p1p1 1.pcap
Switching network driver for p1p1 to netmap bypass mode... failed!
 Switching network driver for p1p1 to normal mode... 
Fatal Error: failed to open device p1p1: interface p1p1 is not running - check cables

Other times, it works perfectly.  I can't figure what is changing to make it start or stop working.
I don't believe I am touching anything between runs.

This is Ubuntu "trusty", kernel 3.13.0-46-generic, tcpreplay 4.1.0
It does spew these in dmesg, but I'm not sure if this is an error or not:

[  192.656954] 591.997129 [ 798] generic_netmap_dtor       Restored native NA           (null)
[  192.732153] 592.072358 [ 798] generic_netmap_dtor       Restored native NA           (null)
[  193.907506] 593.248153 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  193.984582] 593.325258 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.055555] 593.396257 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.115410] 593.456135 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.170826] 593.511572 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.225990] 593.566756 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.281374] 593.622163 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.336509] 593.677317 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.391669] 593.732498 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.447076] 593.787926 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.502231] 593.843102 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.557623] 593.898515 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[  194.776502] ixgbe 0000:05:00.0 p1p1: detected SFP+: 5
[  199.006891] ixgbe 0000:05:00.0 p1p1: detected SFP+: 5
[  209.313559] ixgbe 0000:05:00.0 p1p1: NIC Link is Up 10 Gbps, Flow Control: RX/TX

Here is a trace if it helps:

# strace tcpreplay --netmap -t -i p1p1 1.pcap
execve("/usr/local/bin/tcpreplay", ["tcpreplay", "--netmap", "-t", "-i", "p1p1", "1.pcap"], [/* 23 vars */]) = 0
brk(0)                                  = 0x1897000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62fbb20000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=29154, ...}) = 0
mmap(NULL, 29154, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f62fbb18000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f62fb53b000
mprotect(0x7f62fb6f6000, 2093056, PROT_NONE) = 0
mmap(0x7f62fb8f5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f62fb8f5000
mmap(0x7f62fb8fb000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f62fb8fb000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62fbb17000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62fbb15000
arch_prctl(ARCH_SET_FS, 0x7f62fbb15740) = 0
mprotect(0x7f62fb8f5000, 16384, PROT_READ) = 0
mprotect(0x660000, 4096, PROT_READ)     = 0
mprotect(0x7f62fbb22000, 4096, PROT_READ) = 0
munmap(0x7f62fbb18000, 29154)           = 0
brk(0)                                  = 0x1897000
brk(0x18b8000)                          = 0x18b8000
fcntl(2, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
geteuid()                               = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55da9f80)    = 0
close(3)                                = 0
socket(PF_NETLINK, SOCK_RAW, 0)         = 3
bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
getsockname(3, {sa_family=AF_NETLINK, pid=17988, groups=00000000}, [12]) = 0
sendto(3, "\24\0\0\0\22\0\1\3!\271\31U\0\0\0\0\0\0\0\0", 20, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 20
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"d\4\0\0\20\0\2\0!\271\31UDF\0\0\0\0\4\3\1\0\0\0I\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3368
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"h\4\0\0\20\0\2\0!\271\31UDF\0\0\0\0\1\0\4\0\0\0\2\20\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3376
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"h\4\0\0\20\0\2\0!\271\31UDF\0\0\0\0\1\0\7\0\0\0\2\20\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3384
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"h\4\0\0\20\0\2\0!\271\31UDF\0\0\0\0\1\0\f\0\0\0\2\20\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3384
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"h\4\0\0\20\0\2\0!\271\31UDF\0\0\0\0\1\0\17\0\0\0\2\20\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3380
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0!\271\31UDF\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
sendto(3, "\24\0\0\0\26\0\1\3\"\271\31U\0\0\0\0\0\0\0\0", 20, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 20
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"D\0\0\0\24\0\2\0\"\271\31UDF\0\0\2\10\200\376\1\0\0\0\10\0\1\0\177\0\0\1"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 224
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"@\0\0\0\24\0\2\0\"\271\31UDF\0\0\n\200\200\376\1\0\0\0\24\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 640
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0\"\271\31UDF\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
close(3)                                = 0
socket(PF_PACKET, SOCK_RAW, 768)        = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr=00:00:00:00:00:00}) = 0
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
bind(3, {sa_family=AF_PACKET, proto=0x03, if1, pkttype=PACKET_HOST, addr(0)={0, }, 20) = 0
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_AUXDATA, [1], 4) = 0
getsockopt(3, SOL_PACKET, PACKET_HDRLEN, [36], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RESERVE, [4], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, "\0\0\2\0\20\0\0\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7f62fb33b000
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
munmap(0x7f62fb33b000, 2097152)         = 0
close(3)                                = 0
socket(PF_PACKET, SOCK_RAW, 768)        = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="em1", ifr_hwaddr=c4:34:6b:b9:bb:2c}) = 0
ioctl(3, SIOCGIFINDEX, {ifr_name="em1", ifr_index=2}) = 0
bind(3, {sa_family=AF_PACKET, proto=0x03, if2, pkttype=PACKET_HOST, addr(0)={0, }, 20) = 0
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_AUXDATA, [1], 4) = 0
getsockopt(3, SOL_PACKET, PACKET_HDRLEN, [36], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RESERVE, [4], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, "\0\0\2\0\20\0\0\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7f62fb33b000
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
munmap(0x7f62fb33b000, 2097152)         = 0
close(3)                                = 0
socket(PF_PACKET, SOCK_RAW, 768)        = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="p1p1", ifr_hwaddr=90:e2:ba:7a:47:00}) = 0
ioctl(3, SIOCGIFINDEX, {ifr_name="p1p1", ifr_index=18}) = 0
bind(3, {sa_family=AF_PACKET, proto=0x03, if18, pkttype=PACKET_HOST, addr(0)={0, }, 20) = 0
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_AUXDATA, [1], 4) = 0
getsockopt(3, SOL_PACKET, PACKET_HDRLEN, [36], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RESERVE, [4], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, "\0\0\2\0\20\0\0\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7f62fb33b000
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
munmap(0x7f62fb33b000, 2097152)         = 0
close(3)                                = 0
openat(AT_FDCWD, "/sys/class/net", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
getdents(3, /* 17 entries */, 32768)    = 408
lstat("/sys/class/net/lo/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="lo", ifr_flags=IFF_UP|IFF_LOOPBACK|IFF_RUNNING}) = 0
lstat("/sys/class/net/em4/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="em4", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/em1/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="em1", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
lstat("/sys/class/net/em2/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="em2", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/em3/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="em3", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p3p1/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p3p1", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p3p2/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p3p2", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p3p3/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p3p3", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p3p4/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p3p4", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p2p4/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p2p4", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p2p1/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p2p1", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p2p2/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p2p2", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p2p3/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p2p3", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p1p1/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p1p1", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
lstat("/sys/class/net/p1p2/ifindex", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
ioctl(4, SIOCGIFFLAGS, {ifr_name="p1p2", ifr_flags=IFF_BROADCAST|IFF_MULTICAST}) = 0
getdents(3, /* 0 entries */, 32768)     = 0
close(4)                                = 0
close(3)                                = 0
socket(PF_PACKET, SOCK_DGRAM, 768)      = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
setsockopt(3, SOL_PACKET, PACKET_AUXDATA, [1], 4) = 0
getsockopt(3, SOL_PACKET, PACKET_HDRLEN, [36], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RESERVE, [4], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, "\0\0\2\0\20\0\0\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7f62fb33b000
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
munmap(0x7f62fb33b000, 2097152)         = 0
close(3)                                = 0
socket(PF_BLUETOOTH, SOCK_RAW, 1)       = 3
ioctl(3, HCIGETDEVLIST, 0x18a2120)      = 0
close(3)                                = 0
openat(AT_FDCWD, "/sys/bus/usb/devices", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
getdents(3, /* 18 entries */, 32768)    = 496
open("/dev/usbmon1", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usb/usbmon/1t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usbmon/1t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/dev/usbmon2", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usb/usbmon/2t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usbmon/2t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/dev/usbmon3", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usb/usbmon/3t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usbmon/3t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/dev/usbmon4", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usb/usbmon/4t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usbmon/4t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/dev/usbmon5", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usb/usbmon/5t", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/kernel/debug/usbmon/5t", O_RDONLY) = -1 ENOENT (No such file or directory)
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
socket(PF_NETLINK, SOCK_RAW, 12)        = 3
close(3)                                = 0
socket(PF_NETLINK, SOCK_RAW, 12)        = 3
sendto(3, "\34\0\0\0\1\4\5\0\"\271\31U\0\0\0\0\2\0\0\0\5\0\1\0\4\0\0\0", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0\"\271\31UDF\0\0\0\0\0\0\34\0\0\0\1\4\5\0\"\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, "\34\0\0\0\1\4\5\0#\271\31U\0\0\0\0\2\0\0\0\5\0\1\0\3\4\5\0", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0#\271\31UDF\0\0\0\0\0\0\34\0\0\0\1\4\5\0#\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, "\34\0\0\0\1\4\5\0$\271\31U\0\0\0\0\0\0\0\0\5\0\1\0\1\4\5\0", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0$\271\31UDF\0\0\0\0\0\0\34\0\0\0\1\4\5\0$\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, " \0\0\0\1\4\5\0%\271\31U\0\0\0\0\0\0\0\0\n\0\2\0\0\0\0D\2\0\0\0", 32, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 32
recvfrom(3, "$\0\0\0\2\0\0\0%\271\31UDF\0\0\0\0\0\0 \0\0\0\1\4\5\0%\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
close(3)                                = 0
socket(PF_NETLINK, SOCK_RAW, 12)        = 3
sendto(3, "\34\0\0\0\2\3\5\0&\271\31U\0\0\0\0\0\0\0\0\10\0\1\0\4\0\0\2", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0&\271\31UDF\0\0\0\0\0\0\34\0\0\0\2\3\5\0&\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, "\34\0\0\0\2\3\5\0'\271\31U\0\0\0\0\0\0\0\0\10\0\1\0\3\0\0\2", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0'\271\31UDF\0\0\0\0\0\0\34\0\0\0\2\3\5\0'\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, "\34\0\0\0\2\3\5\0(\271\31U\0\0\0\0\0\0\0\0\10\0\1\0\1\0\0\0", 28, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 28
recvfrom(3, "$\0\0\0\2\0\0\0(\271\31UDF\0\0\0\0\0\0\34\0\0\0\2\3\5\0(\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
sendto(3, " \0\0\0\2\3\5\0)\271\31U\0\0\0\0\0\0\0\0\t\0\2\0\0\0\0D\2\271\31U", 32, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 32
recvfrom(3, "$\0\0\0\2\0\0\0)\271\31UDF\0\0\0\0\0\0 \0\0\0\2\3\5\0)\271\31U"..., 1024, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 36
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = -1 ENXIO (No such device or address)
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = -1 ENXIO (No such device or address)
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = 0
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = 0
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = -1 ENXIO (No such device or address)
close(3)                                = 0
open("/dev/netmap", O_RDWR)             = 3
ioctl(3, 0xc03c6991, 0x7fff55daa030)    = 0
close(3)                                = 0
openat(AT_FDCWD, "/dev/char", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
getdents(3, /* 188 entries */, 32768)   = 5040
getdents(3, /* 0 entries */, 32768)     = 0
mmap(NULL, 4722688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62fb0ba000
openat(AT_FDCWD, "/usr/local/sbin", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
brk(0x18db000)                          = 0x18db000
getdents(4, /* 2 entries */, 32768)     = 48
getdents(4, /* 0 entries */, 32768)     = 0
brk(0x18d3000)                          = 0x18d3000
close(4)                                = 0
openat(AT_FDCWD, "/usr/local/bin", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
getdents(4, /* 9 entries */, 32768)     = 280
access("/usr/local/bin/tcpreplay", R_OK|X_OK) = 0
close(4)                                = 0
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/local", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/local/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/local/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/local/bin/.tcpreplayrc", 0x7fff55da8f20) = -1 ENOENT (No such file or directory)
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/local", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/local/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/local/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/local/bin/.tcpreplayrc", 0x7fff55da8f20) = -1 ENOENT (No such file or directory)
stat("p1p1", 0x7fff55daa170)            = -1 ENOENT (No such file or directory)
open("/dev/netmap", O_RDWR)             = 4
ioctl(4, 0xc03c6991, 0x7fff55daa0a0)    = 0
close(4)                                = 0
open("/dev/netmap", O_RDWR)             = 4
write(2, "Switching network driver for p1p"..., 59Switching network driver for p1p1 to netmap bypass mode... ) = 59
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
nanosleep({1, 0}, 0x7fff55da9e50)       = 0
ioctl(4, 0xc03c6992, 0x7fff55daa060)    = 0
mmap(NULL, 343019520, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0) = 0x7f62e6999000
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
nanosleep({4, 0}, 0x7fff55da9e50)       = 0
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 5
ioctl(5, SIOCGIFFLAGS, {ifr_name="p1p1", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_MULTICAST}) = 0
close(5)                                = 0
write(2, "failed!", 7failed!)                  = 7
write(2, "\n", 1
)                       = 1
write(2, " Switching network driver for p1"..., 53 Switching network driver for p1p1 to normal mode... ) = 53
munmap(0x7f62e6999000, 343019520)       = 0
close(4)                                = 0
write(2, "\nFatal Error: failed to open dev"..., 88
Fatal Error: failed to open device p1p1: interface p1p1 is not running - check cables

) = 88
exit_group(-1)                          = ?
+++ exited with 255 +++

thanks for any pointers.

**Comment by eapster123** [comment]
I think I figured this out, the default of 4 seconds wasn't enough for the interface on the switch to come back up.  I'm now using "--nm-delay=15" and it seems to work.  I did change it to an "edge" (portfast), port, but it is still takes longer than 4 seconds to become operational.

**Comment by fklassen** [comment]
Glad you found it. You are the second one to report this. I will leave this open and consider increasing the delay slightly.

Any idea what the minimum reliable delay is?

**Comment by eapster123** [comment]
According to this, the entire down/up cycle is 34 seconds, but I have been successful using --nm-delay set to 15 seconds.

2015 Mar 31 14:18:12 SW %ETHPORT-5-IF_DOWN_LINK_FAILURE: Interface Ethernet1/9 is down (Link failure)
2015 Mar 31 14:18:46 SW %ETHPORT-5-SPEED: Interface Ethernet1/9, operational speed changed to 10 Gbps
2015 Mar 31 14:18:46 SW %ETHPORT-5-IF_DUPLEX: Interface Ethernet1/9, operational duplex mode changed to Full
2015 Mar 31 14:18:46 SW %ETHPORT-5-IF_RX_FLOW_CONTROL: Interface Ethernet1/9, operational Receive Flow Control state 
changed to off
2015 Mar 31 14:18:46 SW %ETHPORT-5-IF_TX_FLOW_CONTROL: Interface Ethernet1/9, operational Transmit Flow Control state
 changed to off
2015 Mar 31 14:18:46 SW %ETHPORT-5-IF_UP: Interface Ethernet1/9 is up in mode access

**Comment by fklassen** [comment]
Thanks for the update.

That is crazy long. I don't think I can change defaults to accommodate your situation. Eventually we want to get `quick_tx` feature stable, which is much easier to install and does not require a reset. It compile on most systems without requiring kernel source.

 I will close this as "info" status so others can reference your situation.
