### ISSUE TITLE
Unable to get `--fragroute` option to work with tcpreplay-edit

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#180]
Library versions built and used:
        Libdnet-1.11
        Libpcap-1.6.2
        Libevent-2.0.22
        Fragroute-1.2
        Tcpreplay-4.1.0
FYI: tcpreplay was configured with: ./configure --enable-dynamic-link

Version info for built tcpreplay & tcpreplay-edit :

        # tcpreplay -V

        tcpreplay version: 4.1.0 (build git:v4.1.0)
        Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta Inc.
        Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
        The entire Tcpreplay Suite is licensed under the GPLv3
        Cache file supported: 04
        Compiled against libdnet: 1.11
        Compiled against libpcap: 1.6.2
        64 bit packet counters: enabled
        Verbose printing via tcpdump: enabled
        Packet editing: disabled
        Fragroute engine: enabled
        Injection method: PF_PACKET send()
        Not compiled with netmap

        # tcpreplay-edit -V

        tcpreplay version: 4.1.0 (build git:v4.1.0)
        Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta Inc.
        Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
        The entire Tcpreplay Suite is licensed under the GPLv3
        Cache file supported: 04
        Compiled against libdnet: 1.11
        Compiled against libpcap: 1.6.2
        64 bit packet counters: enabled
        Verbose printing via tcpdump: enabled
        Packet editing: enabled
        Fragroute engine: enabled
        Injection method: PF_PACKET send()
        Not compiled with netmap

Platform:
        SUSE Linux Enterprise Server 11 (x86_64)
        VERSION = 11
        PATCHLEVEL = 3
        LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"

Network cards:
        Not relevant due to not wanting to transmit and using tcpreplay-edit.

Command line used ( following format outlined on http://tcpreplay.synfin.net/wiki/tcprewrite (at bottom of page) ):

        tcpreplay-edit --fragroute=frag.cfg --infile=gtpu_IPv4_GTPU_IPv6.pcap --outfile=gtpu_IPv4_GTPU_IPv6_frags.pcap

           where frag.cfg contains:
                ip_frag 500

**Comment by fklassen** [comment]
I have never played with the `--fragroute` option so it took me a while to get my head around it. I think I know enough now to address it.

I was able to get it to work. First I downloaded, compile and install [libdnet-1.11](http://libdnet.sourceforge.net/) on Linux. It is incorrect to attempt to install it with `apt-get`. Then I ran `./configure && make` in tcpreplay.

Looking at your command example, I see some issues:
* You state that you want to produce a pcap file instead of sending it through an interface. Therefore you should be using `tcprewrite` instead of `tcpreplay-edit`
* Your `frag.cfg` file contains `500`, which is smaller than the minimum `512` allowed by IPv4.
* From the title of your pcap files, it appears that you are attempting to fragment IPv6 packets. Although fragmentation of IPv6 is technically possible, it almost certainly is not supported by the [fragroute](http://www.monkey.org/~dugsong/fragroute/) code that has been embedded into Tcpreplay suite. IPv6 requires an additional header and lots of manipulation to get it to work. That just won't happen with Tcpreplay.

Here is an example of how I got it to work. 
* Unzip the `1500.pcap.zip` file.
* Create a frag.cfg file that contains:
```
ip_frag 512 
```
* run the following command to produce the fragmented `512.pcap` (attached)
```
tcprewrite --fragroute=frag.cfg --infile=1500.pcap --outfile=512.pcap
```
[1500.pcap.zip](https://github.com/appneta/tcpreplay/files/67595/1500.pcap.zip)
[512.pcap.zip](https://github.com/appneta/tcpreplay/files/67601/512.pcap.zip)

**Comment by Fabusafat** [comment]
Dear Prof. 

Please could you help into install Fragrout with tcpreplay. I am trying do it and I did as you mention but it not works due to Fragroute not Install at either Ubuntu 16,18 or Debian. 

Please,  could you help me. 

Thank you so much

**Comment by mik1904** [comment]
@Fabusafat I have installed tcpreplay with IP fragmentation support as explained above on Ubuntu 20.04 LTS.
The steps are the following:
1. Download and install the libdnet 1.1.1 library
2. Download and install the stable version of [tcpreplay](https://tcpreplay.appneta.com/wiki/installation.html#download-releases) compiling the source code (no apt install) as explained above by @fklassen

**Comment by HollaHieu** [comment]
@Fabusafat I know this is late but what works for me is adding this line after you install libdnet-1.11:
`sudo ln -s /usr/local/lib/libdnet.1 /usr/lib/x86_64-linux-gnu/libdnet.1`
and proceed doing as @fklassen said
