### ISSUE TITLE
What is the basis for the ipv4 and ipv6 randomization code?

### ISSUE THREAD

**Issue by signalsensefred** [appneta/tcpreplay#196]
In src/tcpedit/edit_packet.c, the functions randomize_ipv4_addr and randomize_ipv6_addr have no comment on why the algorithm they use is desirable or what proprties it has. Is there a reference somewhere explaining why this is the right thing to do?

**Comment by fklassen** [comment]
I didn't write the code, but it appears to be used for replaying ARP packets. I can imaging if an ARP is using real (original) address, it could really mess up a network if replayed without modifying IP addresses.

If you need more info, I suggest posting on tcpreplay-users@lists.sourceforge.net where the original authors hang out.
