### ISSUE TITLE
# tcpreplay or netmap-master bugs

### ISSUE THREAD

**Issue by laulpt** [appneta/tcpreplay#197]
Hello Mr. Fred Klassen,

I am using tcpreplay 4.1.0 and netmap-master from this link: https://github.com/luigirizzo/netmap/tree/master/LINUX
I am using VM ware workstation to run ubuntu 14.04.2 i386 as virtual machine.
Linux kernel version: 3.19.5
I compiled netmap-master ok by following step:
./configure
make
sudo make install
I also compiled tcpreplay ok by following step:
./configure --with-netmap=/home/tuong/work/netmap-master/
make
sudo make install
Could you help me solve this problem below? It is a bug on netmap or tcpreplay?
Thank you so much!
Tuong

I replayed packets and got errors following:
#
tuong@ubuntu:~/work/netmap-master-new/LINUX$ ethtool -i eth0
driver: pcnet32
version: 1.35
firmware-version: 
bus-info: 0000:02:01.0
supports-statistics: no
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
tuong@ubuntu:~/work$ sudo tcpreplay -i eth0 -t -K --netmap smallFlows.pcap 
Switching network driver for eth0 to netmap bypass mode... Warning: ioctl error -1 35142:31
failed!
 Switching network driver for eth0 to normal mode... 
Fatal Error: failed to open device eth0: nm_do_ioctl: Operation not supported
tuong@ubuntu:~/work$ tail /var/log/syslog
Aug 12 06:18:59 ubuntu kernel: [ 8993.514239] 5812 pages reserved
Aug 12 06:18:59 ubuntu kernel: [ 8993.514240] 0 pages cma reserved
Aug 12 06:18:59 ubuntu kernel: [ 8993.514242] 539.261932 [1083] netmap_finalize_obj_allocator Unable to create cluster at 49120 for 'netmap_buf' allocator
Aug 12 06:18:59 ubuntu kernel: [ 8993.515806] 539.263496 [1986] netmap_do_regif           lut f8eba000 bufs 24559 size 2048
Aug 12 06:19:03 ubuntu avahi-daemon[873]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::20c:29ff:fe99:6a50.
Aug 12 06:19:03 ubuntu avahi-daemon[873]: Joining mDNS multicast group on interface eth0.IPv6 with address 2408:210:8ac3:db00:9176:28d7:ed8f:35ae.
Aug 12 06:19:03 ubuntu kernel: [ 8997.917675] 543.669103 [ 800] generic_netmap_dtor       Restored native NA   (null)
Aug 12 06:19:03 ubuntu avahi-daemon[873]: Registering new address record for 2408:210:8ac3:db00:9176:28d7:ed8f:35ae on eth0.*.
Aug 12 06:19:03 ubuntu avahi-daemon[873]: Withdrawing address record for fe80::20c:29ff:fe99:6a50 on eth0.
Aug 12 06:19:03 ubuntu avahi-daemon[873]: Registering new address record for 2408:210:8ac3:db00:20c:29ff:fe99:6a50 on eth0.*.

tuong@ubuntu:~/work$ lsmod
Module                  Size  Used by
ixgbe                 235635  0 
netmap                107320  1 ixgbe
quick_tx               50876  0 
nfnetlink_queue        17780  0 
nfnetlink_log          17538  0 
nfnetlink              14288  2 nfnetlink_log,nfnetlink_queue
ptp                    18861  1 ixgbe
pps_core               18758  1 ptp
mdio                   13345  1 ixgbe
dca                    14642  1 ixgbe
bnep                   18895  2 
rfcomm                 58005  8 
snd_ens1371            24524  2 
snd_ac97_codec        105700  1 snd_ens1371
ac97_bus               12642  1 snd_ac97_codec
gameport               15287  1 snd_ens1371
iosf_mbi               13317  0 
snd_pcm                88316  2 snd_ac97_codec,snd_ens1371
snd_seq_midi           13324  0 
snd_seq_midi_event     14475  1 snd_seq_midi
snd_rawmidi            25681  2 snd_ens1371,snd_seq_midi
coretemp               13201  0 
snd_seq                56592  2 snd_seq_midi_event,snd_seq_midi
snd_seq_device         14454  3 snd_seq,snd_rawmidi,snd_seq_midi
crc32_pclmul           12987  0 
snd_timer              28486  2 snd_pcm,snd_seq
snd                    66629  11 snd_ac97_codec,snd_timer,snd_pcm,snd_seq,snd_rawmidi,snd_ens1371,snd_seq_device
aesni_intel            18170  0 
vmwgfx                146336  3 
btusb                  31648  0 
aes_i586               16995  1 aesni_intel
soundcore              14599  1 snd
xts                    12749  1 aesni_intel
serio_raw              13210  0 
bluetooth             424483  22 bnep,btusb,rfcomm
lrw                    13057  1 aesni_intel
gf128mul               14503  2 lrw,xts
ablk_helper            13357  1 aesni_intel
cryptd                 15578  1 ablk_helper
vmw_balloon            13191  0 
ttm                    81012  1 vmwgfx
drm_kms_helper        104834  1 vmwgfx
ppdev                  17363  0 
lp                     13299  0 
drm                   270437  6 ttm,drm_kms_helper,vmwgfx
parport_pc             32021  0 
shpchp                 32143  0 
parport                40768  3 lp,ppdev,parport_pc
vmw_vmci               60631  0 
i2c_piix4              17734  0 
mac_hid                13059  0 
hid_generic            12503  0 
usbhid                 46993  0 
hid                    95905  2 hid_generic,usbhid
mptspi                 22184  2 
psmouse               100191  0 
mptscsih               38998  1 mptspi
pcnet32                40608  0 
ahci                   25587  0 
mptbase                95667  2 mptspi,mptscsih
libahci                30872  1 ahci
mii                    13654  1 pcnet32
scsi_transport_spi     25744  1 mptspi
pata_acpi              12901  0 
floppy                 59642  0 
#

**Comment by fklassen** [comment]
I am quite certain that netmap is not supported on VMware workstation. You will most likely have to run it on a real machine. The *Operation not supported* error above is coming from netmap, so you will have to go https://github.com/luigirizzo/netmap/issues for support.
