### ISSUE TITLE
# tcpreplay with netmap support cannot send packets with high rate of packets

### ISSUE THREAD

**Issue by laulpt** [appneta/tcpreplay#198]
Dear Mr. Fred Klassen,

I am trying to send packets with netmap support to get high speed of traffic. However, I met an issue as shown below. It did not give a high speed of sending packets. It is clear that 2,820,000 packets took a long time at 10.07 seconds. This rate is very slow. Could you help me why this rate is very slow?
I am running on Ubuntu 14.10 Linux Kernel 3.19.5, tcpreplay 4.0.1, netmap from this thread: https://github.com/luigirizzo/netmap
My hardware is 4 cores, Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz.

Thank you so much!
Lau Phi Tuong

reem@reempc:~/workodroid/netmap-master/LINUX/ixgbe$ ethtool -i eth0
driver: e1000e
version: 2.3.2-k
firmware-version: 0.13-4
bus-info: 0000:00:19.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
reem@reempc:~/workodroid$ sudo tcpreplay -i eth0 --loop 20000 -tK --netmap test.pcap
Switching network driver for eth0 to netmap bypass mode... done!
File Cache is enabled
Actual: 2820000 packets (1254080000 bytes) sent in 10.07 seconds.
Rated: 116618800.0 Bps, 932.95 Mbps, 262236.07 pps
Flows: 37 flows, 3.44 fps, 2800000 flow packets, 20000 non-flow
Statistics for network device: eth0
	Attempted packets:         2820000
	Successful packets:        2820000
	Failed packets:            0
	Truncated packets:         0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0
Switching network driver for eth0 to normal mode... done!
reem@reempc:~/workodroid/netmap-master/LINUX/ixgbe$ lsmod
Module                  Size  Used by
ixgbe                 258125  0 
mdio                   13561  1 ixgbe
dca                    15130  1 ixgbe
netmap                123777  1 
nfnetlink_queue        22279  0 
nfnetlink_log          17886  0 
nfnetlink              14726  2 nfnetlink_log,nfnetlink_queue
radeon               1552945  3 
rfcomm                 69461  0 
bnep                   19543  2 
bluetooth             488615  10 bnep,rfcomm
ttm                    97373  1 radeon
drm_kms_helper        121796  1 radeon
snd_hda_codec_realtek    83873  1 
intel_rapl             19289  0 
snd_hda_codec_generic    68949  1 snd_hda_codec_realtek
iosf_mbi               13541  1 intel_rapl
snd_hda_codec_hdmi     51974  1 
x86_pkg_temp_thermal    14205  0 
snd_hda_intel          30520  5 
drm                   335031  6 ttm,drm_kms_helper,radeon
intel_powerclamp       18786  0 
hid_generic            12559  0 
coretemp               13441  0 
snd_hda_controller     31044  1 snd_hda_intel
usbhid                 52566  0 
kvm_intel             148428  0 
snd_hda_codec         139421  5 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_intel,snd_hda_controller
hid                   114433  2 hid_generic,usbhid
kvm                   475862  1 kvm_intel
snd_hwdep              17698  1 snd_hda_codec
snd_pcm               105485  4 snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_controller
snd_seq_midi           13564  0 
snd_seq_midi_event     14899  1 snd_seq_midi
snd_rawmidi            30827  1 snd_seq_midi
snd_seq                67178  2 snd_seq_midi_event,snd_seq_midi
snd_seq_device         14878  3 snd_seq,snd_rawmidi,snd_seq_midi
snd_timer              29458  2 snd_pcm,snd_seq
parport_pc             32741  0 
ppdev                  17635  0 
mei_me                 19659  0 
lp                     17759  0 
crct10dif_pclmul       14307  0 
crc32_pclmul           13133  0 
snd                    87611  21 snd_hda_codec_realtek,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_seq_device
ghash_clmulni_intel    13230  0 
parport                42264  3 lp,ppdev,parport_pc
mei                    88330  1 mei_me
aesni_intel           169590  0 
dcdbas                 14928  0 
aes_x86_64             17131  1 aesni_intel
lrw                    13287  1 aesni_intel
i2c_algo_bit           13406  1 radeon
i8k                    14696  0 
quick_tx               59489  0 
gf128mul               14951  1 lrw
shpchp                 37040  0 
glue_helper            13944  1 aesni_intel
lpc_ich                21093  0 
ablk_helper            13597  1 aesni_intel
wmi                    19193  0 
cryptd                 20360  3 ghash_clmulni_intel,aesni_intel,ablk_helper
serio_raw              13434  0 
soundcore              15052  2 snd,snd_hda_codec
mac_hid                13227  0 
video                  20271  0 
binfmt_misc            18035  1 
e1000e                234375  0 
psmouse               111567  0 
ptp                    19395  2 ixgbe,e1000e
ahci                   34019  2 
libahci                32190  1 ahci
pps_core               19333  1 ptp

**Comment by abiryukov** [comment]
It is e1000e driver and it's sending at 932.95 Mbps. For this number of packets in this time, average packet size works out to be ~416 bytes, which is reasonable

**Comment by fklassen** [comment]
I would argue that this is as expected for your hardware. In fact, this is very fast. Let's analyze your results.

Looking at packets sent vs bytes sent, your average packet size is ...
```
1254080000 bytes / 2820000 packets = 444.7 bytes (average).
```

Since this is an e1000e driver, we know you are running on a GigE interface. On Ethernet, every packet has additional overhead not reported at Layer 2 (MAC). There are 24 hidden bytes (FSC, Inter-frame Gap, Preamble). So, on a GigE interface, the maximum speed you can theoretically achieve with an average of 444.7 byte frames is
```
444.7 / (444.7 + 24) X 1Gbps = 948Mbps.
```

You achieved `932.95 Mbps`, which is just 15.8Mbps from saturated. That is 98.5% of theoretical max.

Now, why did you not get 100%, as shown in some of my GigE and 10GigE examples? I go back to the fact that you are running an e1000e driver. This driver is for Intel's cheapest desktop GigE adapters. I suspect that you may be running a 82574 or even worse, 82583 NIC. Also, if they are wired to the mother board, or you are running more than 2 NICs, you can bet that they are wired to the slower South Bridge. If you were to get a server NIC such as i350, i210 or i211 and plug it into your PCI bus (typically North Bridge), your results would be 100% (948 Mbps for this packet capture).

I find that CPU doesn't matter when using kernel bypass techniques such as `netmap` or `quick tx`. All you need is a good NIC adapter that is plugged into the best PCI slot.

**Comment by fklassen** [comment]
Just saw your comment @abiryukov ... could it be I got the average packet size wrong? If so, this link is running near theoretical max.

**Comment by abiryukov** [comment]
No, yours look correct @fklassen . I missed bytes sent, and just did an estimate based on Mbps

**Comment by laulpt** [comment]
Dear fklassen, 

How can i increase the number of packets to cause traffic? I mean how can i change to 10GigE?

**Comment by fklassen** [comment]
Closing issue. Results look good.
