### ISSUE TITLE
replay is at higher rate than specified by -M

### ISSUE THREAD

**Issue by maverickprateek** [appneta/tcpreplay#200]
I have ubuntu 14.04 LTS.
tcpreplay version is the latest available for ubuntu.

I am seeing tcpreplay sending packets with Actual speed exceeding the speed limit.
If I mention -M 51, the Actual speed is ~51
If I mention -M 100, the Actual speed is ~102

tcpreplay --version
tcpreplay version: 3.4.4 (build 2450) (debug)
Copyright 2000-2010 by Aaron Turner <aturner at synfin dot net>
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.5.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Injection method: PF_PACKET send()

I am seeing that the actual speed is more than what I specified -
tcpreplay -K -q -i eth6 -M 100 -l 500 -L 10000000 maccdc2012_00005.pcap
Actual: 10000000 packets (2954122420 bytes) sent in 219.78 seconds.		Rated: 13441270.0 bps, 102.55 Mbps, 45500.05 pps
Statistics for network device: eth6
	Attempted packets:         10000000
	Successful packets:        10000000
	Failed packets:            0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0

Let me know if/what more information is needed.

**Comment by maverickprateek** [comment]
pcaps can be found at "http://www.netresec.com/?page=MACCDC"

**Comment by fklassen** [comment]
You are running a very old version. I think you will find this fixed in version 4.X releases. https://github.com/appneta/tcpreplay/releases

**Comment by maverickprateek** [comment]
It is indeed fixed in 4.1.0.

**Comment by fklassen** [comment]
Thanks for updating and closing.
