### ISSUE TITLE
Tcpreplay needs a "live" interface?

### ISSUE THREAD

**Issue by b-u-g-s** [appneta/tcpreplay#201]
Hi, 

I am wondering if anyone could help me with a problem with tcpreplay, I am not sure if it is a bug or if I am doing something wrong/it is by design... 
I have a pcap from a computer/network. 
I want to use that pcap on my IDS (on a completely different network/environment). On this computer I have 2 NIC: 1) eth0 a live primary interface with an IP assigned and 2) eth1 a monitoring interface in promisc mode, no IP.

- if I do tcpreplay -t -i eth0 my.pcap
I can see the traffic being replayed (just using etherape to have a visual cue and also can see alerts in my IDS)

- if I do tcpreplay -t -i eth1 my.pcap
then nothing seems to be replayed... although tcpreplay tells me it has replayed the traffic

now... if I plug a cable into my eth1 interface ... and do tcpreplay -t -i eth1 my.pcap then it works!
but the idea, is that I want to replay in offline mode...

any ideas why this happens?
looks like tcpreplay can only replay on an interface which is "live" with "real" traffic going through it.
I have tried with tcpreplay version 3.4.4 and 4.1.0 on Debian Jessie 8 (SELKS distro) in a VMware virtual machine. eth0 is my wifi and eth1 is the ethernet built-in adaptor.
I have also tried to play with different speed (-x).

One thing to note, is if I try to get a bit more info and enable verbose mode (-v) I get an error:
Fatal Error:
poll() timeout... tcpdump seems to be having a problem keeping up
Try increasing TCPDUMP_POLL_TIMEOUT

But really... why can etherape/my IDS can see tcpreplay traffic on an interface in promiscuous mode with no IP assigned only when there is a network cable and some other traffic going through it? it looks as if tcpreplay is ignored...
I also tried with a static IP address, still no luck. I need to have a cable plugged in.

Thanks,
Bugs.

**Comment by b-u-g-s** [comment]
Well, I found the answer :)
This is because of VMware. If there is no cable plugged in, it seems VMware somehow does not enable the interface... and although it appears to be up in linux when doing ifconfig, in fact it isn't up.
After doing a fair bit of testing with tcpdump and other network tools like nmap and ping... it was obvious no packets were being transmitted even though from a Linux point of view the NIC was up.

The solution? 
To create a dummy device!
http://unix.stackexchange.com/questions/152331/how-can-i-create-a-virtual-ethernet-interface-on-a-machine-without-a-physical-ad

I will write something up at some point, but thought I would post this now in case someone also struggles with this.
B.

**Comment by fklassen** [comment]
Glad you found it. Thanks for posting the solution.

Generally I recommend posting questions on the main forum for tcpreplay <tcpreplay-users@lists.sourceforge.net>. It hits hundreds of users vs. a half dozen or so on GitHub.
