### ISSUE TITLE
Master doesn't compile on OS X 10.11

### ISSUE THREAD

**Issue by DomT4** [appneta/tcpreplay#203]
[Gist log](https://gist.github.com/DomT4/10bf28280d20d57d8ea8).

Note to get that far the `configure.ac` SDK check has to be patched to include 10.11 or `--with-macosx-sdk=10.11` passed on the command line otherwise it panics about not being able to find an appropriate SDK.

**Comment by fklassen** [comment]
I am testing the latest updates to fix may issues with libpcap. Not only is the library change, but also OS X, Debian, Ubuntu are changing how they use it. I hope this fixes several bug that are specific to libpcap.

**Comment by fklassen** [comment]
PR #216 appears to have fixed this. Is in master, and will be generally available soon in 4.1.1-beta3.
