### ISSUE TITLE
Can not replay a tcp packet captured in a pcap file

### ISSUE THREAD

**Issue by jackABA** [appneta/tcpreplay#237]
Hello everyone, I captured a tcp traffic using wireshark and saved the traffic in pcap file. I did two tests:

Test 1:
# tcprewrite --infile=capturedtraffic.pcap --outfile=temp.pcap --srcipmap=0.0.0.0/0:192.168.0.21 --enet-smac=00:0c:29:de:78:42
# tcpreplay --intf1=eth0 temp.pcap

Test 2:
# tcpliveplay eth0 capturedtraffic.pcap 192.168.0.133 00:24:21:1e:29:b2 random

For both tests, the TCP replay didn't work. I'm getting RST. I didn't find also a traffic comming to my TCP server application. Do you have any ideas on how to resolve this problems?

We have already used the iptables command. but we have the same issue. we are getting RST.

Captured data:
![original data](https://cloud.githubusercontent.com/assets/16574753/12141467/d4514dea-b46f-11e5-99f5-baf6c7f42f1f.png)

Test results:
![tcpliveplay output](https://cloud.githubusercontent.com/assets/16574753/12141469/dd6edc80-b46f-11e5-8a9b-85ce84b19bdc.png)

![wireshark error](https://cloud.githubusercontent.com/assets/16574753/12141470/e0dd147c-b46f-11e5-8503-59af66b29c5e.png)

Note that I used Kali Linux. 
Thanks in advance. 
Jack

**Comment by fklassen** [comment]
You cannot replay TCP traffic to a server. The SYN  and SYN/ACK have starting sequence numbers that are random. If either end does not acknowledge the randomly-generated sequence number, the connection is reset. That means that previously-recorded traffic cannot directly replay TCP.

The only solution is to use `tcpliveplay`. It will take a single-flow TCP packet capture and replay it to a server. It will modify sequence numbers appropriately to satisfy the TCP protocol.
