### ISSUE TITLE
`tcpprep` Seg Fault if not using `--pcap` parameter

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#242]
As reported by @synfinatic on IRC channel:

```
<eddy>  hi there, I am using tcpreplay 4.1.0-1 as it is latest in ArchLinux repos and I found out that if I forget to specify --pcap parameter when using tcpprep, it segfaults
<eddy>  hth, thanks for making tcpreplay! :)
```

**Comment by dsrana1212** [comment]
Is this fixed? I think I can take it up. I have some free time at my disposal.

**Comment by fklassen** [comment]
Yes!!! Please!!! ... I would like to get a micro release out be the end of the month, but my real job keeps getting in the way.

**Comment by fklassen** [comment]
I'll move this to v4.2.0 for now. Want to get v4.1.2 out soon.

**Comment by fklassen** [comment]
Unable to recreate. Please provide steps to reproduce.

**Comment by fklassen** [comment]
Closing. Unable to reproduce
