### ISSUE TITLE
Merge "Enhancement_208_pthreads" branch

### ISSUE THREAD

**Issue by teknoraver** [appneta/tcpreplay#243]
Please merge the branch "Enhancement_208_pthreads" to have multithreading enabled under *NIX

**Comment by fklassen** [comment]
Waiting for response to my question ...

```
Also, in the past I have found that multiple threads usually performs more poorly than single threaded. I have a 1.2Ghz ARM processor that is able to saturate GigE. Is there a purpose for multi-threading that I am not aware of?
```

My concern is that mult-threading can cause packet reordering at higher rates. It also tends to slow things down.

What is the purpose of this PR, and why would people benefit from it?

**Comment by fklassen** [comment]
closing as per comments above
