### ISSUE TITLE
fragroute engine fails to fragment the IP datagrams generated by wireshark with TCP Segmentation offloading enabled.

### ISSUE THREAD

**Issue by dsrana1212** [appneta/tcpreplay#246]
On windows systems with TCP segmentation offloading enabled, the IP fragmentation is done by the NIC card and the IP layer sets the ip_total_len field in header to 0. This field is populated by the NIC appropriately. Since wireshark sniffs packets before they are passed on to NIC, the sniffed IP datagrams have large payload with ip_total_len set to 0 in header.

 Fragroute fragments the ip datagrams by reading the length from ip->tol_len field. Since this field is zero in above scenario, the datagrams are not fragmented.

**Comment by dsrana1212** [comment]
I submitting a fix in pkt.c file in fragroute library to address the issue.

**Comment by fklassen** [comment]
Merged PR. Leaving open until documentation/testing complete.

**Comment by dsrana1212** [comment]
Thanks. Will update the Doc and post complete testing results shortly

**Comment by fklassen** [comment]
OK, if you do updates, add fix to CHANGELOG and add yourself to the contributors list.

**Comment by dsrana1212** [comment]
Sure.

**Comment by fklassen** [comment]
Update in master
