### ISSUE TITLE
TCPDump and TCPReplay to record and replay requests to application servers

### ISSUE THREAD

**Issue by nipunarora** [appneta/tcpreplay#248]
Can TCPDump and TCPReplay be used to record(tcpdump) network traffic coming in to a application server/webserver/queue application etc., and then replayed using the dump on TCPReplay? 

Let's say I setup a apache server and use TCPDump to capture the entire network traffic and dump it to a file. Now I run apache in a different machine and want to replay the traffic to this new apache server using the file. How can I achieve this? 

I especially want to understand how TCPReplay would work in such a scenario. i.e. how would syn/ack responses work for TCP. How would a new a connection etc. be initiated?

**Comment by fklassen** [comment]
No, see FAQ. You cannot replay traffic to a server.

**Comment by fklassen** [comment]
close issue as answered
