### ISSUE TITLE
unsupported radiotap header,tcprewrite segfault

### ISSUE THREAD

**Issue by marian3** [appneta/tcpreplay#249]
Hi, I have a problem:
`:~$ sudo tcpdump -i mon0 -s0 -w - > pipeffplay` 
mon0-wifi interface in mode monitor
`:~$ sudo tcpreplay -i lo pipeffplay`
`Warning: Unsupported physical layer type 0x0304 on lo.  Maybe it works, maybe it wont.  See tickets #123/318`
`Warning: Unable to process unsupported DLT type: 802.11 plus radiotap header (0x7f)`
`Warning: Unable to process unsupported DLT type: 802.11 plus radiotap header (0x7f)`
and after:
`:~$ tcprewrite --dlt=enet --infile=mon0.pcap --outfile=output.pcap`
`Segmentation fault (bol uložený výpis pamäte)`

`:~$ tcpreplay -V`
`Warning: May need to run as root to get access to all network interfaces.
tcpreplay version: 4.1.1-beta3 (build git:v4.1.1-beta3)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.7.4
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Injection method: PF_PACKET send()
Not compiled with netmap`

**Comment by fklassen** [comment]
Upgrade to release code and try again. If it doesn't work, please attach a packet capture and I'll have a look.

So, what is the adapter? It appears to be some type of tap device.

**Comment by marian3** [comment]
Compiling source from GitHub:
`CC       pppserial.o`
`  AR       libtcpedit.a`
`ar: u' modifier ignored since D' is the default (see U')`
`make[4]: Leaving directory '/home/marian/tcpreplay-master/src/tcpedit'`
`make[3]: Leaving directory '/home/marian/tcpreplay-master/src/tcpedit'`
`make[3]: Entering directory '/home/marian/tcpreplay-master/src'`
`  CC       tcpreplay-tcpreplay_opts.o`
`tcpreplay_opts.c: In function ‘translate_option_strings’:`
`tcpreplay_opts.c:1713:9: error: ‘option_usage_text’ undeclared (first use in this function)`
`     if (option_usage_text.field_ct != 0) {`
`         ^`
`compilation terminated due to -Wfatal-errors.`
`Makefile:907: recipe for target 'tcpreplay-tcpreplay_opts.o' failed`
`make[3]: *** [tcpreplay-tcpreplay_opts.o] Error 1`
`make[3]: Leaving directory '/home/marian/tcpreplay-master/src'`
`Makefile:1158: recipe for target 'all-recursive' failed`
`make[2]: *** [all-recursive] Error 1`
`make[2]: Leaving directory '/home/marian/tcpreplay-master/src'`
`Makefile:571: recipe for target 'all' failed`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory '/home/marian/tcpreplay-master/src'`
`Makefile:453: recipe for target 'all-recursive' failed`
`make: *** [all-recursive] Error 1`
Adapter is usb_wifi card.

**Comment by fklassen** [comment]
download release code

https://github.com/appneta/tcpreplay/releases

**Comment by marian3** [comment]
release code works the same way

**Comment by marian3** [comment]
release 4.1.1
`:~$ sudo tcprewrite --dlt=enet --infile=mon0.pcap --outfile=output.pcap`
`Warning: Packet 1 is unknown reason for non-data
tcprewrite: ./plugins/dlt_ieee80211/ieee80211.c:237: dlt_ieee80211_proto: Assertion pktlen >= l2len failed.`

**Comment by fklassen** [comment]
really looks like you got the wrong code if you cannot compile. Compiling from GitHub is only for developers who have all prereqs install. Release code has docs etc. compiled and can be compiled by nearly anyone. https://github.com/appneta/tcpreplay/releases/download/v4.1.1/tcpreplay-4.1.1.tar.gz

**Comment by marian3** [comment]
Capture file:
[mon0.zip](https://github.com/appneta/tcpreplay/files/303469/mon0.zip)

**Comment by fklassen** [comment]
good ... this is proving it is an unsupported network type. What type of adapter is this? It doesn't appear to be a normal wireless.

**Comment by marian3** [comment]
ok,compiled release code no problem.
Its normal usb_wireles edimax ew-7318usg(realtek), or  tplink wn 722n(atheros). AP is tplink.
In mode_managed its work - ethernet header. In mode_monitor not work - radiotap header.

**Comment by fklassen** [comment]
May be a bug. I'll mark it as such and will put in the backlog.

**Comment by marian3** [comment]
thanks.

**Comment by marian3** [comment]
the problem may be in the:
`~$ tcprewrite --dlt=enet --infile=mon0.pcap --outfile=output.pcap -v`
`reading from file -, link-type EN10MB (Ethernet)`
`tcpdump: pcap_loop: bogus savefile header`
it is possible to do something about it?

**Comment by fklassen** [comment]
don't understand. clarify.

**Comment by marian3** [comment]
something about it here [http://osdir.com/ml/network.tcpdump.devel/2007-03/msg00050.html](url)

**Comment by fklassen** [comment]
OK, I think I understand. Appears to not be a bug. Closing for now.

**Comment by Anilpmeasure** [comment]
what is the fix for this issue? Tried checking using above mentioned link http://osdir.com/ml/network.tcpdump.devel/2007-03/msg00050.html) and looks like it is broken..
