### ISSUE TITLE
"Error=Cannot allocate memory" with multiple, simulanteous tcpreplay sessions

### ISSUE THREAD

**Issue by epearce2** [appneta/tcpreplay#252]
If I fire up 4 different tcpreplay sessions on the same machine, using a different interface each time, the fourth session gives me a "Cannot allocate memory" error.   Is there some setting I can tweak for this?  I've done this in the past with a different server in the past without issues.  

/usr/local/bin/tcpreplay -K --loop=1000 --nm-delay=15 --netmap -t -i p3p1 foo.pcap

This is from strace:

open("/dev/netmap", O_RDWR)             = 4
write(2, "Switching network driver for p3p"..., 59Switching network driver for p3p2 to netmap bypass mode... ) = 59
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
nanosleep({1, 0}, 0x7fff84a91680)       = 0
ioctl(4, 0xc03c6992, 0x7fff84a91890)    = -1 ENOMEM (Cannot allocate memory)
close(4)                                = 0
write(2, "\nFatal Error: failed to open dev"..., 177
Fatal Error: failed to open device p3p2: Failure accessing netmap.
        Request for netmap version 11 failed.
        Compiled netmap driver is version 11.
        Error=Cannot allocate memory

) = 177
exit_group(-1)                          = ?
+++ exited with 255 +++

 /usr/local/bin/tcpreplay --version
tcpreplay version: 4.1.1 (build git:v4.1.1)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.5.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Default injection method: PF_PACKET send()
Optional injection method: netmap

Linux 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 14.04
128GB of RAM
SuperMicro H8QGL 
3 x Intel 520 cards

**Comment by fklassen** [comment]
@epearce2 somehow this fell through the cracks. I don't recall seeing this question when you assigned it earlier.

My first question is, how large is the packet capture? I notice that you are using the `-K` command. That means that the entire packet capture must be loaded into memory before sending. If you have 4 instances running, the packet capture is loaded 4 times.

Also, I would be interested in the output of `free -m` command.

**Comment by fklassen** [comment]
Attempted to recreate issue. I don't have any problems. I suggest using a smaller capture file, or do not preload the pcap file into memory (i.e. do not use the `-K` option).
