### ISSUE TITLE
Quick TX on Ubuntu 14.04 SegFaults

### ISSUE THREAD

**Issue by epearce2** [appneta/tcpreplay#253]
I've tried several OS combinations of Ubuntu and CentOS, and I haven't been able to get QTX mode working.  I'm happy to supply whatever debugging inf might help.

/usr/local/bin/tcpreplay -i qtx:p3p1 foo.pcap
Segmentation fault

This is from strace:

mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0) = 0x7f5869630000
rt_sigaction(SIGUSR1, {0x405eb0, [USR1], SA_RESTORER|SA_RESTART, 0x7f5899abecb0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCONT, {0x405da0, [CONT], SA_RESTORER|SA_RESTART, 0x7f5899abecb0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x405d50, [INT], SA_RESTORER|SA_RESTART, 0x7f5899abecb0}, {SIG_DFL, [], 0}, 8) = 0
open("foo.pcap", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=2048005516, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f589a2b6000
read(5, "\324\303\262\241\2\0\4\0\0\0\0\0\0\0\0\0\377\377\0\0\1\0\0\0\373\305gW\323s\f\0"..., 4096) = 4096
brk(0xbce000)                           = 0xbce000
ioctl(4, SNDCTL_SEQ_RESET, 0x7f589a0e80c0) = 0
read(5, "\377\305N\5\326\252\201\203\320\325\200\276\n\2:2\221D\224N\355\245O\16\24\212\27\371\205\361\243\""..., 4096) = 4096
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f589a0e1736} ---
+++ killed by SIGSEGV +++
Segmentation fault

/usr/local/bin/tcpreplay --version
tcpreplay version: 4.1.1 (build git:v4.1.1)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.5.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Default injection method: PF_PACKET send()
Optional injection method: Quick TX
Not compiled with netmap

Linux 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 14.04
128GB of RAM
SuperMicro H8QGL 
3 x Intel 520 cards

**Comment by fklassen** [comment]
Dropping support for Quick TX until a maintainer becomes available #357
