### ISSUE TITLE
macOS: Xcode shouldn't be required if the Command Line Tools are installed

### ISSUE THREAD

**Issue by ilovezfs** [appneta/tcpreplay#254]
Although it was not the case in tcpreplay 4.1.0, the tcpreplay 4.1.1 release now requires Xcode.app. This is a regression in that the Command Line Tools from Apple are actually sufficient to build tcpreplay (both 4.1.0 and 4.1.1) even if you don't have Xcode.app.

The problem is that configure in 4.1.1 is looking for an Xcode SDK folder, but such a folder will only exist if Xcode.app is installed. However, once configure finds the SDK folder, the path is used only to set the value of isysroot. It turns out that if you have the Command Line Tools, it is sufficient to set isysroot to "/" or even not to set it at all.

In the Homebrew formula, so that we do not need to require Xcode.app unnecessarily when the user has the Command Line Tools, I'm making the following replacements in configure when Xcode.app isn't installed:

```
        s.gsub! /^.*Could not figure out the location of a Mac OS X SDK.*$/,
                "MACOSX_SDK_PATH=\"\""
        s.gsub! " -isysroot $MACOSX_SDK_PATH", ""
```

**Comment by fklassen** [comment]
Fixed with PR #265.

Here is a `configure` with Xcode....
```
checking if malloc debugging is wanted... no
checking build system type... x86_64-apple-darwin16.1.0
checking host system type... x86_64-apple-darwin16.1.0
checking target system type... x86_64-apple-darwin16.1.0
checking what macOS compiler to use... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
checking for cygwin development environment... no
```
and here is a build without Xcode, picking up HomeBrew install....

```
checking if malloc debugging is wanted... no
checking build system type... x86_64-apple-darwin16.1.0
checking host system type... x86_64-apple-darwin16.1.0
checking target system type... x86_64-apple-darwin16.1.0
checking what macOS compiler to use... legacy
checking for cygwin development environment... no
```

**Comment by fklassen** [comment]
Still have some build issues

**Comment by fklassen** [comment]
Working now
