### ISSUE TITLE
 I am using tcpreplay to send traffic . I know the -p option for packet per second, but I want to send packet per minute.

### ISSUE THREAD

**Issue by vipkum2** [appneta/tcpreplay#270]
I am using tcpreplay to send traffic . I know the -p option for packet per second, but I want to send packet per minute.

**Comment by fklassen** [comment]
Thanks for your request. Adding to feature request backlog.

**Comment by fklassen** [comment]
#287 allow fractions for `--pps`, for example `--pps 0.25`

**Comment by vipkum2** [comment]
thanks if I want to send lets say 100 pks per minute then I need to do - --pps .100

**Comment by fklassen** [comment]
Not so simple. For 100 packets per minute, you need 60 / 100. Specifically `--pps 0.6`.

**Comment by vipkum2** [comment]
OK Sir,
Thank you..

Regards,
Vipin
