### ISSUE TITLE
Ability to replace vlan tag by specifying a range would be nice..

### ISSUE THREAD

**Issue by ckannan** [appneta/tcpreplay#273]
Currently I can replace a vlan tag on the pcap file like this to send packets...

tcpreplay-edit -i ens6f1 -t -K -l 0 --enet-vlan=add --enet-vlan-pri=0 --enet-vlan-tag=500 --enet-vlan-cfi=0 vlan_single.pcap

It would be nice if I can do ... "--enet-vlan-tag=500-510"

tcpreplay-edit -i ens6f1 -t -K -l 0 --enet-vlan=add --enet-vlan-pri=0 --enet-vlan-tag=500-510 --enet-vlan-cfi=0 vlan_single.pcap

**Comment by fklassen** [comment]
I don't understand what this enhancement would do. What would be the effect of "--enet-vlan-tag=500-510"? Need specifics.

**Comment by fklassen** [comment]
waiting for feedback
