### ISSUE TITLE
cross-compilation fail with musl-libc

### ISSUE THREAD

**Issue by cpackham** [appneta/tcpreplay#275]
Hi Fred,

Just reporting in from buildroot with a build failure for tcpreplay when using musl as the libc[1]

````
In file included from /home/peko/autobuild/instance-1/output/host/usr/arm-buildroot-linux-musleabihf/sysroot/usr/include/linux/if_tun.h:20:0,
                 from sendpacket.c:160:
/home/peko/autobuild/instance-1/output/host/usr/arm-buildroot-linux-musleabihf/sysroot/usr/include/linux/if_ether.h:141:8: error: redefinition of 'struct ethhdr'
 struct ethhdr {
        ^
````

According to the musl FAQ[2] the fix is to avoid including linux/if_tun.h. Looks like thats what socat ended up doing [3]. If I get a chance I'll send a PR unless someone else fixes it first.

[1] - http://autobuild.buildroot.net/results/dde/dde54ccefa32af1f46a4af5b6caed822c3209dfc/build-end.log
[2] - http://wiki.musl-libc.org/wiki/FAQ#Q:_why_am_i_getting_.22error:_redefinition_of_struct_ethhdr.2Ftcphdr.2Fetc.22_.3F
[3] - https://github.com/openwrt/packages/pull/1386/commits/a0968fae

**Comment by fklassen** [comment]
Hi, I would appreciate a PR, but I don't want to disable the ability to replay on Tun/Tap devices. Possibly we can add a `./configure --disable-tun-tap` option. Better yet, we can try to find a way to support both on musl.

**Comment by fklassen** [comment]
Closing as won't fix. Need to be able to detect musl inclusion automatically so we don't break other builds.
