### ISSUE TITLE
Unable to replay a pcap on a tap

### ISSUE THREAD

**Issue by guillaume-u** [appneta/tcpreplay#279]
Hello,

Replay on a tap device, doesn't seems to work in v4.X (but it worked on v3.X) — at least on Gentoo distribution.

The result of **./configure** give me :
`Tuntap device support:      yes`

The result of **tcpreplay -V** :
```
tcpreplay version: 4.1.1 (build git:v4.1.1)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.12
Compiled against libpcap: 1.7.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: enabled
Injection method: PF_PACKET send()
Not compiled with netmap
```

To reproduce it, you can use this pcap [ptpv2.pcap](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=ptpv2.pcap)

And execute these commands :
```
 ip tuntap add mode tap tap0
 ifconfig tap0 up
 tcpreplay -itap0 /tmp/ptpv2.pcap
```

I hope you can reproduce it.

Thanks,

Guillaume.

**Comment by fklassen** [comment]
Hi Guillaume. Unfortunately I have to close this as "won't fix". It appears to be a bug in OpenSSL. I call the OpenSSL API `pcap_findalldevs` to get all the interfaces. There appears to be an issue where tap interfaces are not discovered by OpenSSL when running as super user.

Work around ... run `tcpreplay` as a regular user when compiled with a newer version of OpenSSL.
