### ISSUE TITLE
Enhance --unique-ip option to modify IPs every few loops in addition to every loop

### ISSUE THREAD

**Issue by abiryukov** [appneta/tcpreplay#296]
This would allow some control of new flows ratio vs traffic rate, while replaying the same file, providing more consistency in test setup.
Options for implementing could be:
* adding optional integer parameter to --unique-ip, indicating number of loops with keeping the same IP values (defaulting to a value for switching IPs at every loop)
* if that is undesirable, introducing a new option, for example --unique-ip-loops

**Comment by fklassen** [comment]
@abiryukov we should discuss how this feature would be implemented. 

* what would be the name of the option? e.g. `--ratio-unique-ip`
* what parameters would be passed to it? e.g. `1`
* what would be the be the behavior of this parameter? e.g. what happens when the parameter is `2`

**Comment by fklassen** [comment]
Discussed further with @abiryukov offline. Issue is that optional arguments are not well supported across platforms, and additional options are not desirable in tcpreplay. Will attempt to make this work in a branch and then decide if this gets merged.

**Comment by fklassen** [comment]
Attempt at `--unique-ip-loops` option, but using float values:

*  `--unique-ip-loops=0` - invalid
*  `--unique-ip-loops=1` - default - packet modified every loop
*  `--unique-ip-loops=2` - packet modified every other loop
*  `--unique-ip-loops=1.5` - packet modified 2 out of 3 loops

Fractions will cause bursty flow traffic and is probably more valid for very small files. For now, will not fully document this behavior as it may be confusing.

**Comment by fklassen** [comment]
Working in Release4.2
