### ISSUE TITLE
--unique-ip flag no longer seems to be effective

### ISSUE THREAD

**Issue by c-f-s-s** [appneta/tcpreplay#346]
This issue seems to have been introduced in v4.2 (my 4.1.2 systems with identical hardware do not reproduce).

When I run tcpreplay as such:

sudo tcpreplay-edit -i ix1 --unique-ip --netmap -M 5000 -K -l 0 <replay file>

and capture only traffic matching an IP pair filter (based off of an IP pair in the original pcap) I find that I continuously receive traffic matching this filter. I've tested this for several minutes at a time with tcpreplay looping through the pcap about 4 times a minute.

This was initially reproduced with a very large pcap, but it seems to reproduce regardless of the size/variety of the data.

### Environment info
_tcpreplay -v:_
tcpreplay version: 4.2.0 (build git:v4.2.0)
Copyright 2013-2016 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.12
Compiled against libpcap: 1.4.0
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: enabled
Default injection method: bpf send()
Not compiled with Quick TX
Optional injection method: netmap

_uname -rsp:_
FreeBSD 10.3-RELEASE amd64

_packet blaster:_
10Gb Intel Ethernet Converged Network Adapter X520-SR2

**Comment by fklassen** [comment]
@c-f-s-s I'll try to reproduce tonight. Thanks for catching this.

**Comment by fklassen** [comment]
Target for 4.2.1
