### ISSUE TITLE
Error tcpreplay_opts.h

### ISSUE THREAD

**Issue by patricia93sousa** [appneta/tcpreplay#359]
I'm trying to make and make install this but, after:

> ./autogen.sh

and 

> ./configure

Then, I make: 

> sudo make && sudo make install

" , but i got the error:

```
"tcpreplay_opts.h:61:3: error: #error option template version mismatches autoopts/options.h header
 # error option template version mismatches autoopts/options.h header"
```

**Comment by fklassen** [comment]
What platform are you on? Do you plan to do development? If not, you should get a copy of the release from SourceForge or https://github.com/appneta/tcpreplay/releases. It doesn't required building of man pages, `configure` etc. It doesn't get this error.

If you plan to do development work, you will have to set up your local machine properly. It looks like your local copy of `libopts` is incompatible. That library is a bit of a mess and is very version dependent. Try compiling with `./configure --disable-local-libopts`. That will force the use of the copy of libopts shipped with the source.

**Comment by patricia93sousa** [comment]
I install the release and it works. Thanks.
