### ISSUE TITLE
Build Tcpreplay with PF Ring's Libpcap: `PF_RING libpcap no`

### ISSUE THREAD

**Issue by nickwallen** [appneta/tcpreplay#395]
How can I verify that tcpreplay is using the PF_RING version of libpcap correctly?  When I run the configure script it reports `PF_RING libpcap             no`.   I would expect it to read `yes`.   Any tips?

Here are the steps that I have taken on a host running CentOS 7.2.  First, I installed PF_RING along with its libpcap library.
```
PREFIX=/usr/local
# download
wget https://github.com/ntop/PF_RING/archive/6.6.0.tar.gz -O - | tar -xz

# build kernel module
cd PF_RING-6.6.0/kernel
./configure --prefix=$PREFIX
make && make install

# build userland libs
cd ../userland/lib
./configure --prefix=$PREFIX
make && make install

# build pfring's libpcap
cd ../userland/libpcap
./configure --prefix=$PREFIX
make && make install
```

Then I download the tcpreplay source code and attempt to build it with the pfring libpcap library that I just installed.
```
wget https://github.com/appneta/tcpreplay/releases/download/v4.2.5/tcpreplay-4.2.5.tar.gz -O - | tar -xz
cd tcpreplay-4.2.5/
./configure --with-libpcap=/usr/local/ --with-pfring-lib=/usr/local/lib/libpfring.a
```

As part of the output, I see `pcap_get_pfring_id... none required` which I am not sure if that is a problem or not.
```
...
checking for library containing pcap_get_pfring_id... none required
checking for library containing pcap_close... none required
....
##########################################################################
             TCPREPLAY Suite Configuration Results (4.2.5)
##########################################################################
libpcap:                    /usr/local/ (>= 0.9.6)
PF_RING libpcap             no   /usr/local/lib/libpfring.a
libdnet:                    /usr   1.12
autogen:                    /usr/bin/autogen (autogen (GNU AutoGen) 5.18)
Use libopts tearoff:        yes
64bit counter support:      yes
tcpdump binary path:        /usr/sbin/tcpdump
fragroute support:          yes
tcpbridge support:          yes
tcpliveplay support:        yes

Supported Packet Injection Methods (*):
Linux TX_RING:              no
Linux PF_PACKET:            yes
BSD BPF:                    no
libdnet:                    yes
pcap_inject:                yes
pcap_sendpacket:            yes **
pcap_netmap                 no
Linux/BSD netmap:           no
Tuntap device support:      yes

* In order of preference; see configure --help to override
** Required for tcpbridge
```

Many thanks

**Comment by nickwallen** [comment]
Here is my config.log
[config.log.txt](https://github.com/appneta/tcpreplay/files/1005033/config.log.txt)

**Comment by fklassen** [comment]
Logging as a bug. It is not reporting PF_RING when in fact it is being used.

This bug will not get scheduled for a while. I just released 4.2.6, and am planning a code freeze once Debian/Ubuntu packaging has stabilized.

**Comment by nickwallen** [comment]
Is there any work around?  Can I edit the configure script to always assume PF_RING just so I can get this built?

**Comment by nickwallen** [comment]
I traced through the configure script.  If I use the ` --enable-static-link` flag, I can work around this issue.

```
./configure --with-libpcap=/usr/local/ --with-pfring-lib=/usr/local/lib/libpfring.a --enable-static-link
```

**Comment by fklassen** [comment]
Thanks. I'll add that to a README.

Please let me know what performance you get. Last time I tried I got marginally better performance, probably due to some issues deep inside PF_Ring. I have been considering trying again with a newer version to see if performance has been improved. I would expect wire rates at 10GigE +.

**Comment by fklassen** [comment]
Found that a PF-RING specific libpcap instruction is included in the `configure` script. It appears that you have found another way of making it work (as documented above).

```
./configure -h | grep pfring -A3
  --with-pfring-lib       Use a specific PF_RING static library when using
                          PF_RING libpcap.

                          Usage:     --with-pfring-lib=<library>
                          e. g.: --with-pfring-lib=/usr/lib/libpfring_zc_x86_64.a
```
