### ISSUE TITLE
Tcpreplay with PF_Ring ZC - Failed to open device zc:enp129s0f1

### ISSUE THREAD

**Issue by nickwallen** [appneta/tcpreplay#396]
I was able to build tcpreplay against PF_Ring ZC libpcap.  I outlined the steps in #395 .  Now when I try to run using the "zc:eth0"-style naming convention that I see used in #117, tcpreplay fails with the following error.

```
$ tcpreplay -i zc:enp129s0f1 ~/pcaps/example.pcap

Fatal Error: failed to open device zc:enp129s0f1: ioctl: No such device
```

It seems like my PF_Ring install is OK, since I am able to use their `zsend` utility.

```
$ zsend -i zc:enp129s0f1 -c 1 -g 0 -f ~/pcaps/example.pcap -r 1.0 -n 0
Sending packets to zc:enp129s0f1
Estimated CPU freq: 2487464000 Hz
=========================
Absolute Stats: 12'779'019 pkts - 1'073'437'596 bytes
=========================
..
```

Is there another step I need to take with tcpreplay so that it can use the libpcap library driven by PF_Ring ZC?  Any ideas on where I can dig further?

**Comment by fklassen** [comment]
Try not using the `zc:` suffix. The idea of using a modified libpcap is that the program you compile against (in this case Tcpreplay) does not not have to be aware of underlying media. The `zc:` suffix can only be recognized by programs that are specifically written for PF_Ring.

This is the line that is causing the failure https://github.com/appneta/tcpreplay/blob/master/src/common/sendpacket.c#L995

**Comment by fklassen** [comment]
If using the procedures outlined in #395 to build with PF_RING libpcap, this should work. Please reopen if you run into any issues.
