### ISSUE TITLE
-T flag breaks traffic replay timing; ioport isn't recognized

### ISSUE THREAD

**Issue by c-f-s-s** [appneta/tcpreplay#419]
Couple of similar issues here. When I attempt to run a pcap at captured rate using either of the non-default timers "nano" or or "select," every packet is replayed with a time delta of less than one microsecond (if used with netmap, further details in reproduction info).

The second issue is that ioport doesn't seem to be recognized. When I attempt to run with ioport, I get the following error:
_Fatal Error: Unable to parse args: Unsupported timer mode: ioport_

I'm not familiar with ioport so I'm not sure if what it's trying to call simply isn't available in Unix or what...

Running explicitly with the default gtod doesn't negatively affect the replay rate.

### Setup info:
Same as for [issue 418](https://github.com/appneta/tcpreplay/issues/418).

### Reproduction info:
For the timing issue... as stated above, if nano or select are used in conjunction with netmap, all packets seemed to be sent out within a microsecond of each other.

However, if used without netmap, tcpreplay _does seem to try to honor time deltas,_ however the accuracy with which they are replayed is _far_ worse than with gdot. Something tells me that at least the nano API is supposed to provide more reliable timing. Packet timings without --netmap are usually pretty spot on, typically a couple of microseconds at worst, but these flags cause the timings to be off by milliseconds.

Example runs:
(inaccurate timing) sudo tcpreplay -i ix1 -T nano <pcap file>
(invariably <1 μs timing) sudo tcpreplay -i ix1 --netmap -T nano <pcap file>

**Comment by fklassen** [comment]
Need to update CHANGELOG and do some cleanup.
