### ISSUE TITLE
DLT conversion and portmap can't be done in the same pass

### ISSUE THREAD

**Issue by verticelo** [appneta/tcpreplay#429]
Just reporting this in case it isn't known:

If one runs with options --dlt and -r at the same time, then -r will not be executed.

If one runs --dlt and then on the output runs -r then it will be executed properly.

**Comment by fklassen** [comment]
This worked for me. I changed the MAC addresses and the port numbers as expected. Please send examples.

    ./src/tcprewrite -i test.pcap -o /tmp/bug_249-2.pcap --dlt=user --user-dlink=00,50,da,5d,46,55,0,7,eb,30,a4,c3,08,0 -r 80:8080
