### ISSUE TITLE
Tcpreplay resends pcap automatically in the night 

### ISSUE THREAD

**Issue by voilaviola** [appneta/tcpreplay#469]
Hello,
I am testing my IDS by replaying pcaps with tcprewrite and tcpreplay, and I noticed a strange thing during my test. I used tcprewrite to change the ips of pcap1.pcap to public ips, and then used tcpreplay to send it to IDS. Here's what I found in my IDS:
![image](https://user-images.githubusercontent.com/9637973/38797568-2d982724-415f-11e8-9e2c-b85429065982.png)
I replayed pcap1.pcap at around 15h, but I got 2 beaconings of same alert(same alert type, source and destination) in the night. My Wireshark and firewall records do have captured the same packets in the night, that means tcpreplay is still sending the pcap 4 hours after it stopped.
This is the only pcap that I found bizzare. The same issue doesn't occur when I replay other pcaps.
By the way, the alert triggered by this pcap is _[snort]ET INFO UPnP Discovery Search Response vulnerable UPnP device 2_
The original pcap1.pcap does not have such a time distribution, so I assume it has nothing to do with the timestamp in pcap. Is it possible that tcpreplay continues sending pcaps in the buffer after it stops?

Please find here the commands I used:
_sudo tcprewrite -s 423 --fixcsum -v -d -i pcap0.pcap -o pcap1.pcap
sudo tcpreplay -i eth1 pcap1.pcap_

Thank you in avdance,

**Comment by fklassen** [comment]
What version are you running?

**Comment by voilaviola** [comment]
I'm using tcpreplay and tcprewrite 3.4.4

**Comment by fklassen** [comment]
That is very old. I suggest using [the latest version](https://github.com/appneta/tcpreplay/releases/latest). Let me know if you still see the failure.

**Comment by voilaviola** [comment]
Hi, I updated tcpreplay and it 's solved. Please close this issue, and thanks again

**Comment by fklassen** [comment]
👍
