### ISSUE TITLE
Remove dead code in services.c

### ISSUE THREAD

**Issue by gy741** [appneta/tcpreplay#480]
Hello.

I think, the conditional statement in services.c on line 75 is useless.

Because Due to the 40 line code, the nmatch value is fixed.

So, I think, The if statement is always false.

what do you think?

Thanks.

https://github.com/appneta/tcpreplay/blob/efa2ce43c0ff1c23ae6aebb6dee76ec5b68de234/src/common/services.c#L35-L77

**Comment by fklassen** [comment]
Makes sense. Will look at this for a future release.
