### ISSUE TITLE
Fatal Error: failed to open device enp130s0f0: Failure accessing netmap.

### ISSUE THREAD

**Issue by grantcurell** [appneta/tcpreplay#527]
### Full error:
[root@trafficgenerator ~]# tcpreplay -i enp130s0f0 -M 3000 -l 50000000 --netmap test_pcap.pcap
Switching network driver for enp130s0f0 to netmap bypass mode...
Fatal Error: failed to open device enp130s0f0: Failure accessing netmap.
        Request for netmap version 13 failed.
        Compiled netmap driver is version 13.
        Error=Invalid argument

### With Verbose Debugging:
[root@trafficgenerator ~]# tcpreplay -i enp130s0f0 -M 3000 -l 50000000 --netmap -d 5 smallFlows.pcap
DEBUG1 in netmap.c:sendpacket_open_netmap() line 193: sendpacket_open_netmap: using netmap
DEBUG5 in utils.c:_our_safe_malloc() line 55: Malloc'd 1384 bytes in netmap.c:sendpacket_open_netmap() line 198
DEBUG1 in netmap.c:get_netmap_version() line 65: netmap detected API version 13 which matches compiled version

Switching network driver for enp130s0f0 to netmap bypass mode...
Fatal Error in sendpacket.c:sendpacket_open() line 539:
 failed to open device enp130s0f0: Failure accessing netmap.
        Request for netmap version 13 failed.
        Compiled netmap driver is version 13.
        Error=Invalid argument

This setup was working two days ago with zero problems. Box has been completely untouched. I came back into work today, closed out the old tcpreplay sessions, went to launch a new one and received the above error. Netmap is properly loaded with if_size adjusted according to the interface's buffers and the interface has been loaded with the correctly compiled (and until today) working netmap i40e driver.

OS: Fedora Server 28
Tcpreplay Version: 4.2.6

Edit for more info:
[root@trafficgenerator ~]# tcpreplay --version
tcpreplay version: 4.2.6 (build git:v4.2.6)
Copyright 2013-2017 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.9.0-PRE-GIT
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Default injection method: PF_PACKET send()
Optional injection method: netmap

**Comment by fklassen** [comment]
Duplicate of #424. Fixed in #522 and will be available in version 4.3.

**Comment by grantcurell** [comment]
@fklassen is anything required other than the upgrade? Below are my results.
![image](https://user-images.githubusercontent.com/35169230/48424315-04cc3500-e728-11e8-9fac-d31449bb6caf.png)

**Comment by grantcurell** [comment]
@fklassen still learning netmap - is nr_tx_slots meant to be 0?
```
(gdb) print nmr
$10 = {nr_name = "enp130s0f0\000\000\000\000\000", nr_version = 13, nr_offset = 0, nr_memsize = 0, nr_tx_slots = 0, nr_rx_slots = 0, nr_tx_rings = 0,
  nr_rx_rings = 0, nr_ringid = 0, nr_cmd = 0, nr_arg1 = 0, nr_arg2 = 0, nr_arg3 = 0, nr_flags = 1, spare2 = {0}}
```

According to https://www.freebsd.org/cgi/man.cgi?query=netmap&sektion=4 

> 	   nr_tx_slots, nr_rx_slots - indicate the size of transmit and receive rings.

It seems like that should be a non zero value?

**Comment by grantcurell** [comment]
It would seem it is indeed a problem specific to netmap.

**Comment by fklassen** [comment]
Recreated with Linux 4.14.71 kernel with netmap master (git:11aa43a6).

**Comment by grantcurell** [comment]
Just for giggles I set it up on a box that is identical in every way except the network card. This one has  I used CentOS this time to make sure I was using an "officially" supported system. This one has an Intel 82599ES in it. 

```
           *-network:1
                description: Ethernet interface
                product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
                vendor: Intel Corporation
                physical id: 0.1
                bus info: pci@0000:02:00.1
                logical name: enp2s0f1
                version: 01
                serial: 90:e2:ba:f0:77:a9
                size: 10Gbit/s
                capacity: 10Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical fibre 1000bt-fd 10000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=ixgbe driverversion=5.3.8 duplex=full firmware=0x61bd0001 ip=169.254.233.189 latency=0 link=yes multicast=yes port=fibre promiscuous=yes speed=10Gbit/s
                resources: irq:194 memory:c2100000-c217ffff ioport:5000(size=32) memory:c2200000-c2203fff memory:90200000-902fffff memory:90300000-903fffff
```

In this configuration it makes it past switching the network driver, but hangs:
![image](https://user-images.githubusercontent.com/35169230/48503939-2c46fe80-e809-11e8-839d-9b24093f53bc.png)

Confirmed nothing going out:
![image](https://user-images.githubusercontent.com/35169230/48503966-3c5ede00-e809-11e8-87fc-0174e86a6708.png)

**Comment by fklassen** [comment]
It appears that netmap master is messed up. Running `pkt-gen` I see a failure message suggesting a failure on the ioctl ...

```
$ sudo ./pkt-gen -i eth3 -f tx -b1 -l 1400
699.441712 main [2855] interface is eth3
699.441779 main [2985] running on 1 cpus (have 8)
699.442779 extract_ip_range [467] range is 10.0.0.1:1234 to 10.0.0.1:1234
699.442787 extract_ip_range [467] range is 10.1.0.1:1234 to 10.1.0.1:1234
699.442806 nm_open [853] overriding ARG1 0
699.442810 nm_open [857] overriding ARG2 0
699.442812 nm_open [861] overriding ARG3 0
699.442814 nm_open [865] overriding RING_CFG
699.442817 nm_open [874] overriding ifname eth3 ringid 0x0 flags 0x8001
699.447559 nm_open [945] NIOCREGIF failed: Cannot allocate memory netmap:eth3
699.447575 main [3078] Unable to open netmap:eth3: Cannot allocate memory
699.447579 main [3145] aborting
```

It works I check out the most recent version (11.4)....
```
$ sudo ./pkt-gen -i eth3 -f tx -b1 -l 1400
260.509589 main [2855] interface is eth3
260.509655 main [2985] running on 1 cpus (have 8)
260.510646 extract_ip_range [467] range is 10.0.0.1:1234 to 10.0.0.1:1234
260.510654 extract_ip_range [467] range is 10.1.0.1:1234 to 10.1.0.1:1234
260.510673 nm_open [853] overriding ARG1 0
260.510677 nm_open [857] overriding ARG2 0
260.510680 nm_open [861] overriding ARG3 0
260.510682 nm_open [865] overriding RING_CFG
260.510684 nm_open [874] overriding ifname eth3 ringid 0x0 flags 0x8001
260.816262 main [3083] mapped 334980KB at 0x7f152712d000
Sending on netmap:eth3: 8 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
260.816346 main [3180] Sending 1 packets every  0.000000000 s
260.816377 start_threads [2515] Wait 2 secs for phy reset
262.816478 start_threads [2517] Ready...
262.816595 sender_body [1540] start, fd 3 main_fd 3
262.816632 sender_body [1598] frags 1 frag_size 1400
263.817218 main_thread [2605] 4.085 Kpps (4.088 Kpkts 45.786 Mbps in 1000658 usec) 1.00 avg_batch 0 min_space
264.818214 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1000997 usec) 0.00 avg_batch 99999 min_space
264.822341 sender_body [1623] poll error on queue 0: timeout
265.819215 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1001001 usec) 0.00 avg_batch 99999 min_space
266.820214 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1000999 usec) 0.00 avg_batch 99999 min_space
266.824345 sender_body [1623] poll error on queue 0: timeout
...
```

I'll leave this issue open until a fix arrives in netmap master branch.

**Comment by grantcurell** [comment]
> It appears that netmap master is messed up. Running `pkt-gen` I see a failure message suggesting a failure on the ioctl ...
> 
> ```
> $ sudo ./pkt-gen -i eth3 -f tx -b1 -l 1400
> 699.441712 main [2855] interface is eth3
> 699.441779 main [2985] running on 1 cpus (have 8)
> 699.442779 extract_ip_range [467] range is 10.0.0.1:1234 to 10.0.0.1:1234
> 699.442787 extract_ip_range [467] range is 10.1.0.1:1234 to 10.1.0.1:1234
> 699.442806 nm_open [853] overriding ARG1 0
> 699.442810 nm_open [857] overriding ARG2 0
> 699.442812 nm_open [861] overriding ARG3 0
> 699.442814 nm_open [865] overriding RING_CFG
> 699.442817 nm_open [874] overriding ifname eth3 ringid 0x0 flags 0x8001
> 699.447559 nm_open [945] NIOCREGIF failed: Cannot allocate memory netmap:eth3
> 699.447575 main [3078] Unable to open netmap:eth3: Cannot allocate memory
> 699.447579 main [3145] aborting
> ```
> It works I check out the most recent version (11.4)....
> 
> ```
> $ sudo ./pkt-gen -i eth3 -f tx -b1 -l 1400
> 260.509589 main [2855] interface is eth3
> 260.509655 main [2985] running on 1 cpus (have 8)
> 260.510646 extract_ip_range [467] range is 10.0.0.1:1234 to 10.0.0.1:1234
> 260.510654 extract_ip_range [467] range is 10.1.0.1:1234 to 10.1.0.1:1234
> 260.510673 nm_open [853] overriding ARG1 0
> 260.510677 nm_open [857] overriding ARG2 0
> 260.510680 nm_open [861] overriding ARG3 0
> 260.510682 nm_open [865] overriding RING_CFG
> 260.510684 nm_open [874] overriding ifname eth3 ringid 0x0 flags 0x8001
> 260.816262 main [3083] mapped 334980KB at 0x7f152712d000
> Sending on netmap:eth3: 8 queues, 1 threads and 1 cpus.
> 10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
> 260.816346 main [3180] Sending 1 packets every  0.000000000 s
> 260.816377 start_threads [2515] Wait 2 secs for phy reset
> 262.816478 start_threads [2517] Ready...
> 262.816595 sender_body [1540] start, fd 3 main_fd 3
> 262.816632 sender_body [1598] frags 1 frag_size 1400
> 263.817218 main_thread [2605] 4.085 Kpps (4.088 Kpkts 45.786 Mbps in 1000658 usec) 1.00 avg_batch 0 min_space
> 264.818214 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1000997 usec) 0.00 avg_batch 99999 min_space
> 264.822341 sender_body [1623] poll error on queue 0: timeout
> 265.819215 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1001001 usec) 0.00 avg_batch 99999 min_space
> 266.820214 main_thread [2605] 0.000 pps (0.000 pkts 0.000 bps in 1000999 usec) 0.00 avg_batch 99999 min_space
> 266.824345 sender_body [1623] poll error on queue 0: timeout
> ...
> ```
> I'll leave this issue open until a fix arrives in netmap master branch.

I used to get that "Cannot allocate memory" message. What I did to get around that was I ran an `ethtool -g <interface>`, got the buffer size, and then ran `echo <size> > /sys/module/netmap/parameters/if_size` and that cleared it up for me. I get stuck after that where for whatever reason netmap can't access the interface. That's all assuming the memory error you've got is the same as mine hahaha

**Comment by grantcurell** [comment]
Fixed. I had to learn a couple of things about netmap, but ultimately to resolve this recompiling both tcpreplay and netmap resolved the issue.
