### ISSUE TITLE
netmap illegal option for tcpreplay

### ISSUE THREAD

**Issue by JosiahRegencia** [appneta/tcpreplay#559]
I'm running tcpreplay in an Ubuntu 14.04 VM inside virtualbox. I have installed both tcpreplay and netmap. But when I run`sudo tcpreplay -i eth0 -t -K --loop 500 --unique-ip --netmap smallFlows.pcap`, I receive this error: `/usr/local/bin/tcpreplay: illegal option -- netmap`.

Also, I don't seem to find netmap inside my `/usr/local/bin`.

My tcpreplay version is 4.3.2.

Any suggestions on how to solve this problem? Thanks

**Comment by fklassen** [comment]
You need to install [netmap](http://info.iet.unipi.it/~luigi/netmap/). It's only advised to do so if you are running on bare metal.
