### ISSUE TITLE
[Bug] TCPReplay-Edit --dstipmap returns new network and old host address.

### ISSUE THREAD

**Issue by ReelEmbedded** [appneta/tcpreplay#562]
**Describe the bug**
Using tcpreplay-edit command with the --srcipmap and --dstipmap options, the remapped destination IP is a combination of new network and old host address.

**To Reproduce**
1. tcpreplay-edit -i eth0 --srcipmap=10.183.12.4/24:10.1.1.154/22 --dstipmap=10.213.119.60/24:10.1.3.157/22 mypcap.pcap
2. Observe the actual destination IP will be 10.1.3.60 (Expected 10.1.3.157) with Wireshark.

**Screenshots**
![image](https://user-images.githubusercontent.com/8815366/59134976-7ffe6e00-893a-11e9-9b48-d01c5f4f3aab.png)

**System (please complete the following information):**
 - OS: Debian 8.10
 - Tcpreplay Version 4.3.2 (built from github tag v4.3.2)

**Additional context**
For my application, I was able to fix the bug with the following patch. However, I didn't check to see the impact of other references to remap_ipv4(...).

```
diff --git a/src/tcpedit/edit_packet.c b/src/tcpedit/edit_packet.c
index 740a090..0907b30 100644
--- a/src/tcpedit/edit_packet.c
+++ b/src/tcpedit/edit_packet.c
@@ -746,7 +746,7 @@ remap_ipv4(tcpedit_t *tcpedit, tcpr_cidr_t *cidr, const uint32_t original)

     /* apply the reverse of the mask to the IP */
     mask = mask ^ 0xffffffff;
-    ipaddr = ntohl(original) & mask;
+    ipaddr = ntohl(cidr->u.network) & mask;

     /* merge the network portion and ip portions */
     result = network ^ ipaddr;
```

**Comment by fklassen** [comment]
Any way of getting the original PCAP that produced the error? Often renaming to `*.txt` will allow it to get uploaded.

Does `sudo make test` fail after patch?

**Comment by ReelEmbedded** [comment]
Here's the simplified PCAP that I used to make the screenshot.
[mypcap.pcap.zip](https://github.com/appneta/tcpreplay/files/3267901/mypcap.pcap.zip)

I don't have my laptop that I was running this on, but I will run the `sudo make test` and post the results on Monday. I saw that in the documentation and didn't think to run it after the patch. Unfortunately, I left the laptop at work.

I just realized it may be confusing regarding the Wireshark screenshot in Windows 7 and the stated Debian 8.10 OS. I ran tcpreplay-edit in a virtual machine and ran Wireshark on the host OS.

Great work on this project! This is a very useful tool.

**Comment by ReelEmbedded** [comment]
So, I tried out the test suite on my another virtual machine at home (Debian 9.9) and I broke the tcprewrite_pnat test with my previously suggested change. Now I'm thinking I may have misunderstood the intent of `--pnat` option. I read the documentation stating that it is remapping the IP address, but I think it's remapping the subnet portion only and keeping the original host address. That is the way it is coded and the test case appears.

In the test case for tcprewrite_pnat, It expects (in frame 37 of the PCAP) `96.17.211.172` to be remapped to `172.16.0.172` with the pnat string `-N 96.17.211.0/24:172.16.0.0/24`. If that is correct, I have definitely misunderstood the purpose of `--pnat`. 

Is there another option that is intended to rewrite the entire IP address, including host address, available?

**Comment by ReelEmbedded** [comment]
After talking this over with a coworker, I think the best option for my application is to leave the source alone and use a 32-bit mask with the PNAT options (see the modified command below). By setting the netmask to be 32 bits, it will ensure the the entire IP is overwritten which was the desired behavior.

`tcpreplay-edit -i eth0 --srcipmap=10.183.12.4/32:10.1.1.154/32 --dstipmap=10.213.119.60/32:10.1.3.157/32 mypcap.pcap`
