### ISSUE TITLE
[Bug] Skipbroadcast Flag

### ISSUE THREAD

**Issue by niklasg8** [appneta/tcpreplay#573]
Hi,
I'm having problems activating the --skipbroadcast flag.
If I try, i just get the help list of usable parameters. 
Thanks for any helping comments.

**Comment by fklassen** [comment]
I will attempt to reproduce this issue in upcoming 4.3.3 work

**Comment by fklassen** [comment]
No issues found. Have you followed the man pages?

```
       -b, --skipbroadcast
              Skip rewriting broadcast/multicast IPv4/v6 addresses.

              By default --seed, --pnat and --endpoints will rewrite broadcast and multicast IPv4/v6 and MAC addresses.     Setting this flag will
              keep broadcast/multicast IPv4/v6 and MAC addresses from being rewritten.
```

**Comment by fklassen** [comment]
No response in 11 days. Closing issue.
