### ISSUE TITLE
[Bug] tcpreplay-edit: enet-vlan=add prevents pnat/srcipmap/dstipmap/endpoints

### ISSUE THREAD

**Issue by Musteblume** [appneta/tcpreplay#574]
**Describe the bug**
The replacement of ip addresses don't work in combination with an added vlan tag.
Example:
```
tcpreplay-edit -i eth0 -K -x 1 --loop 0 --enet-vlan=add --enet-vlan-tag=11 --enet-vlan-cfi=0 --enet-vlan-pri=5 --srcipmap=192.168.0.201:10.0.11.6 --dstipmap=239.1.2.0/24:10.0.11.5 --fixcsum test.pcap
```

**To Reproduce**
1. Start tcpreplay-edit with --enet-vlan=add and --pnat/srcipmap/dstipmap/endpoints
2. View interface output with tshark
3. Ip addresses are not replaced

**Expected behavior**
Replacement of ip addresses

**Screenshots**
Original:
![image](https://user-images.githubusercontent.com/22887071/78668958-d8482880-78db-11ea-9cd9-59aafc61f3e2.png)

Command:
![image](https://user-images.githubusercontent.com/22887071/78668740-7ab3dc00-78db-11ea-80d4-6ccda5577e20.png)

Playback:
![image](https://user-images.githubusercontent.com/22887071/78668354-d3cf4000-78da-11ea-8201-0694d65b5dcb.png)

**System (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Tcpreplay Version 4.3.1 and 4.3.2

**Comment by fklassen** [comment]
Works for me in 4.3.3-beta1 (using Debian stretch):

    sudo src/tcpreplay-edit -i ens33 -K --enet-vlan=add --enet-vlan-tag=11 --enet-vlan-cfi=0 --enet-vlan-pri=5 --srcipmap=172.16.11.12:10.0.11.6 --dstipmap=74.125.19.17/24:10.0.11.5 --fixcsum test/test.pcap

![image](https://user-images.githubusercontent.com/1899327/83575047-8be82600-a4e3-11ea-8d91-6208856ddb2f.png)

**Comment by fklassen** [comment]
Close as "cannot reproduce" - tested in 4.3.3-beta1.
