### ISSUE TITLE
[Bug] tcpreplay-edit with --fixcsum crushing IP header when there is a VLAN tag

### ISSUE THREAD

**Issue by jsbarber** [appneta/tcpreplay#583]
Take any IPv4 packet with a VLAN header. Ask tcpreplay-edit to fix the checksums. The IP header's flags field is crushed by the edit.

Start 
`tcpdump -i ethX -w /tmp/result.pcap` in one window.

In another window, play the attached pcap with 
`tcpreplay-edit -i ethX --fixcsum vlan1pkt.pcap` 

[vlan1pkt.zip](https://github.com/appneta/tcpreplay/files/4685654/vlan1pkt.zip)

Kill tcpdump and use wireshark/tshark to examine the packet. See that the IPv4 Flags field has been overwritten with garbage (the checksum value).

**Comment by fklassen** [comment]
Thanks for the PR. Targeting 4.3.3.

**Comment by fklassen** [comment]
Validated fix. Thanks for the PR.

![image](https://user-images.githubusercontent.com/1899327/83366023-413ea080-a361-11ea-9180-91c9d79f056a.png)

**Comment by fklassen** [comment]
Introduced #594. Reopening.

**Comment by fklassen** [comment]
Regression issue fixed in #594. There was nothing wrong with the commits in this issue. Rather the fix exposed a HBO.
