### ISSUE TITLE
[Bug] tcpreplay fails to open already allocated tap0 device

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#651]
**Describe the bug**
Re-opening #411 due to report that this still fails in 4.3.3-2

**To Reproduce**
See #411

**System:**
 - OS: [e.g. macOS]
 - OS version
 - Tcpreplay Version 4.3.3-2

**Additional context**

**Comment by jersey99** [comment]
OS: Debian Testing [bullseye/sid]
5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux

Hope that helps.

**Comment by fklassen** [comment]
Fixed in PR #660
