### ISSUE TITLE
netmap-libpcap not recognized

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#66]
According to Luigi Rizzo, [netmap-libpcap](https://code.google.com/p/netmap-libpcap) doesn't work. Here is his email to me...

there is one thing i wanted to mention:
netmap (and netmap-libpcap) now encode in the device name
all parameters of interest: whether it is a NIC, a VALE port
or a pipe, whether you want to access an individual queue
or the host stack or the master/slave side of a pipe, etc.

The consequence is that we cannot really have an enumerate
routine in netmap-libpcap, and i have been told that tcpreplay
(and i have seen other apps) seems unhappy if the name
is not one returned by the pcap_findalldevs().

So do you know if there is (or, could you provide) a flag
to accept arbitrary device names and skip the match with
the enumeration results ?

thanks
luigi

**Comment by cwitter** [comment]
When running netmap-libpcap configure doesn't work on 4.1.0:

Error:
configure: error: Unable to link libpcap in /usr/local
