### ISSUE TITLE
[Bug] tcpreplay 4.3.4 Multiplier < 1.0 does not work

### ISSUE THREAD

**Issue by sterling-TAS** [appneta/tcpreplay#674]
**Describe the bug**
I am trying to replay a PCAP at a slower speed and it does not seem to work.  The execution time of the command is constant unless the multiplier command-line option is greater than 1.0.

**To Reproduce**
tcpreplay --intf1=eth0 --multiplier=0.5 myCapFile.pcap

**Expected behavior**
I expect that the time for the PCAP to play to double based on my multiplier.

**System (please complete the following information):**
 - OS: Ubuntu 
 - OS version: 18.04
 - Tcpreplay Version:  4.3.4

**Additional context**
It does seem to use the multiplier option only if I loop the data.  The first loop runs at normal speed and the subsequent loops are at the reduced speed.

**Comment by fklassen** [comment]
Probably introduced by PRs #631 and #645

**Comment by fklassen** [comment]
Reverted PR #631 enhancement in PR #699
