### ISSUE TITLE
[Bug]  Darwin Kernel Version 20.4.0 Build Failed

### ISSUE THREAD

**Issue by Liberxue** [appneta/tcpreplay#676]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by tcpreplay configure 4.3.4, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ./configure

## --------- ##

hostname = xxxxx.local
uname -m = arm64
uname -r = 20.4.0
uname -s = Darwin
uname -v = Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101
Kernel configured for up to 8 processors.
8 processors are physically available.
8 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 610 tasks, 3460 threads, 8 processors
Load average: 2.49, Mach factor: 5.50
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/homebrew/opt/sqlite/bin/
PATH: /opt/homebrew/opt/openssl@1.1/bin/
PATH: /opt/homebrew/opt/openjdk/bin/
PATH: /opt/homebrew/bin/
PATH: /opt/homebrew/sbin/
PATH: /usr/local/bin/
PATH: /usr/bin/
PATH: /bin/
PATH: /usr/sbin/
PATH: /sbin/

## ----------- ##

configure:3464: looking for aux files: ltmain.sh compile ar-lib missing install-sh config.guess config.sub
configure:3477:  trying ./config/
configure:3506:   ./config/ltmain.sh found
configure:3506:   ./config/compile found
configure:3506:   ./config/ar-lib found
configure:3506:   ./config/missing found
configure:3488:   ./config/install-sh found
configure:3506:   ./config/config.guess found
configure:3506:   ./config/config.sub found
configure:3622: checking whether to enable maintainer-specific portions of Makefiles
configure:3632: result: yes
configure:3645: checking if malloc debugging is wanted
configure:3664: result: no
configure:3688: checking build system type
configure:3703: result: aarch64-apple-darwin20.4.0
configure:3723: checking host system type
configure:3737: result: aarch64-apple-darwin20.4.0
configure:3757: checking target system type
configure:3771: result: aarch64-apple-darwin20.4.0
configure:3835: checking what macOS compiler to use
configure:3859: result: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
configure:3888: checking for cygwin development environment
configure:3898: result: no
configure:3920: checking for a BSD-compatible install
configure:3993: result: /usr/bin/install -c
configure:4004: checking whether build environment is sane
configure:4059: result: yes
configure:4218: checking for a race-free mkdir -p
configure:4262: result: ./config/install-sh -c -d
configure:4269: checking for gawk
configure:4304: result: no
configure:4269: checking for mawk
configure:4304: result: no
configure:4269: checking for nawk
configure:4304: result: no
configure:4269: checking for awk
configure:4290: found /usr/bin/awk
configure:4301: result: awk
configure:4312: checking whether make sets $(MAKE)
configure:4335: result: yes
configure:4365: checking whether make supports nested variables
configure:4383: result: yes
configure:4517: checking whether make supports nested variables
configure:4535: result: yes
configure:4560: checking whether make supports the include directive
configure:4575: make -f confmf.GNU && cat confinc.out
this is the am__doit target
configure:4578: $? = 0
configure:4597: result: yes (GNU style)
configure:4673: checking for gcc
configure:4705: result: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
configure:5058: checking for C compiler version
configure:5067: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk --version >&5
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:5078: $? = 0
configure:5067: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -v >&5
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: warning: argument unused during compilation: '-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' [-Wunused-command-line-argument]
configure:5078: $? = 0
configure:5067: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:5078: $? = 1
configure:5067: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -qversion >&5
clang: error: unknown argument '-qversion'; did you mean '--version'?
clang: error: no input files
configure:5078: $? = 1
configure:5067: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -version >&5
clang: error: unknown argument '-version'; did you mean '--version'?
clang: error: no input files
configure:5078: $? = 1
configure:5098: checking whether the C compiler works
configure:5120: /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk    conftest.c  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd, missing required architecture arm64 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:5124: $? = 1
configure:5164: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "tcpreplay"
| #define PACKAGE_TARNAME "tcpreplay"
| #define PACKAGE_VERSION "4.3.4"
| #define PACKAGE_STRING "tcpreplay 4.3.4"
| #define PACKAGE_BUGREPORT "https://github.com/appneta/tcpreplay/issues"
| #define PACKAGE_URL "http://tcpreplay.sourceforge.net/"
| #define PACKAGE "tcpreplay"
| #define VERSION "4.3.4"
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:5169: error: in `/Users/xxxx/Code/c/tcpreplay':
configure:5171: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=aarch64-apple-darwin20.4.0
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=aarch64-apple-darwin20.4.0
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=awk
ac_cv_prog_ac_ct_CC='/Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
ac_cv_prog_make_make_set=yes
ac_cv_target=aarch64-apple-darwin20.4.0
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} '\''/Users/xxx/Code/c/tcpreplay/config/missing'\'' aclocal-1.16'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR='/Library/Developer/CommandLineTools/usr/bin/ar'
AUTOCONF='${SHELL} '\''/Users/xxx/Code/c/tcpreplay/config/missing'\'' autoconf'
AUTOGEN=''
AUTOHEADER='${SHELL} '\''/Users/xxx/Code/c/tcpreplay/config/missing'\'' autoheader'
AUTOMAKE='${SHELL} '\''/Users/xxx/Code/c/tcpreplay/config/missing'\'' automake-1.16'
AWK='awk'
CC='/Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
CCDEPMODE=''
CFLAGS=''
COMPILE_FRAGROUTE_FALSE=''
COMPILE_FRAGROUTE_TRUE=''
COMPILE_NETMAP_FALSE=''
COMPILE_NETMAP_TRUE=''
COMPILE_TCPBRIDGE_FALSE=''
COMPILE_TCPBRIDGE_TRUE=''
COMPILE_TCPLIVEPLAY_FALSE=''
COMPILE_TCPLIVEPLAY_TRUE=''
CPP=''
CPPFLAGS=''
CROSS_ARCH=''
CROSS_LD=''
CUT=''
CXX=''
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DMALLOC_LIB=''
DSYMUTIL=''
DUMPBIN=''
ECHO=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
ENABLE_OSX_FRAMEWORKS_FALSE=''
ENABLE_OSX_FRAMEWORKS_TRUE=''
ENABLE_TCPDUMP_FALSE=''
ENABLE_TCPDUMP_TRUE=''
EXEEXT=''
FGREP=''
GL_GENERATE_STDNORETURN_H_FALSE=''
GL_GENERATE_STDNORETURN_H_TRUE=''
GREP=''
GROFF=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_LIBOPTS_FALSE=''
INSTALL_LIBOPTS_TRUE=''
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LDNETINC=''
LDNETLIB=''
LIBOBJS=''
LIBOPTS_CFLAGS=''
LIBOPTS_DIR=''
LIBOPTS_LDADD=''
LIBS=''
LIBTOOL='/Library/Developer/CommandLineTools/usr/bin/libtool'
LIPO=''
LNAVLIB=''
LNAV_CFLAGS=''
LN_S=''
LPCAPINC=''
LPCAPLIB=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MACOSX_SDK_PATH='/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
MAINT=''
MAINTAINER_MODE_FALSE='#'
MAINTAINER_MODE_TRUE=''
MAKEINFO='${SHELL} '\''/Users/xxx/Code/c/tcpreplay/config/missing'\'' makeinfo'
MANIFEST_TOOL=''
MKDIR_P='./config/install-sh -c -d'
NEED_LIBOPTS_FALSE=''
NEED_LIBOPTS_TRUE=''
NETMAPFLAGS=''
NETMAPINC=''
NETMAPINCDIR=''
NETMAPUSERINC=''
NM='/Library/Developer/CommandLineTools/usr/bin/nm'
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='tcpreplay'
PACKAGE_BUGREPORT='https://github.com/appneta/tcpreplay/issues'
PACKAGE_NAME='tcpreplay'
PACKAGE_STRING='tcpreplay 4.3.4'
PACKAGE_TARNAME='tcpreplay'
PACKAGE_URL='http://tcpreplay.sourceforge.net/'
PACKAGE_VERSION='4.3.4'
PATH_SEPARATOR=':'
PCAP_BPF_H_FILE=''
PCAP_CONFIG=''
POSIX_SHELL=''
PRINTF=''
RANLIB='/Library/Developer/CommandLineTools/usr/bin/ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STDNORETURN_H=''
STRIP='/Library/Developer/CommandLineTools/usr/bin/strip'
SYSTEM_STRLCPY_FALSE=''
SYSTEM_STRLCPY_TRUE=''
TCPREPLAY_RELEASE='1'
TCPREPLAY_VERSION='4.3.4'
VERSION='4.3.4'
WORDS_BIGENDIAN_FALSE=''
WORDS_BIGENDIAN_TRUE=''
ac_ct_AR=''
ac_ct_CC='/Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='aarch64-apple-darwin20.4.0'
build_alias=''
build_asan=''
build_cpu='aarch64'
build_os='darwin20.4.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
debug_flag=''
debug_run_time_flag=''
depmod=''
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
extra_debug_flag=''
host='aarch64-apple-darwin20.4.0'
host_alias=''
host_cpu='aarch64'
host_os='darwin20.4.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
insmod=''
install_sh='${SHELL} /Users/xxx/Code/c/tcpreplay/config/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
nic1=''
nic2=''
oldincludedir='/usr/include'
pcncfg=''
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
rmmod=''
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='aarch64-apple-darwin20.4.0'
target_alias=''
target_cpu='aarch64'
target_os='darwin20.4.0'
target_vendor='apple'
tcpdump_path=''
timestamp_trace_flag=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "tcpreplay"
#define PACKAGE_TARNAME "tcpreplay"
#define PACKAGE_VERSION "4.3.4"
#define PACKAGE_STRING "tcpreplay 4.3.4"
#define PACKAGE_BUGREPORT "https://github.com/appneta/tcpreplay/issues"
#define PACKAGE_URL "http://tcpreplay.sourceforge.net/"
#define PACKAGE "tcpreplay"
#define VERSION "4.3.4"

configure: exit 77

## ----------- ##
```
checking whether to enable maintainer-specific portions of Makefiles... yes
checking if malloc debugging is wanted... no
checking build system type... aarch64-apple-darwin20.4.0
checking host system type... aarch64-apple-darwin20.4.0
checking target system type... aarch64-apple-darwin20.4.0
checking what macOS compiler to use... /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
checking for cygwin development environment... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /Library/Developer/CommandLineTools/usr/bin/clang -m64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
checking whether the C compiler works... no
configure: error: in `/Users/xxx/Code/c/tcpreplay':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by fklassen** [comment]
I'll need to see `configure` and `config.log`. It sounds as though it cannot compile a simple C program. Do other programs compile?

What hardware is this?

**Comment by fklassen** [comment]
I suspect this is M1 hardware which makes this a dup of #668

**Comment by Liberxue** [comment]
OK,
Thank you for sparing the precious time to reply the issue
I will continue to focus on #668

**Comment by Liberxue** [comment]
THX My husband
```
export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
sudo brew reinstall autogen
./configure --disable-local-libopts --disable-libopts-install --prefix=/usr/local --disable-local-libopts
sudo make install -r
```
##  tcpreplay -V
```

Warning: May need to run as root to get access to all network interfaces.
tcpreplay version: 4.3.4 (build git:v4.3.4-4-g0ca82e31)
Copyright 2013-2018 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.9.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Injection method: bpf send()
Not compiled with netmap
```
