### ISSUE TITLE
[Bug] Warning: Unable to send packet: Error with PF_PACKET send() [2512]: Message too long (errno = 90)

### ISSUE THREAD

**Issue by claytondukes** [appneta/tcpreplay#680]
**Describe the bug**
I have packets that were captured using: 

```
tcpdump -i ens18 port 601 -nnvvXSs 0 -G 1200 -W 1 -z gzip -w /tmp/$(hostname).pcap
```

I then modified the packets to use my source/dest ip's/macs

These are syslog RFC5424 style events, so some packets can be quite large.

When I try to replay them using tcpreplay, I get:

```
Warning: Unable to send packet: Error with PF_PACKET send() [2512]: Message too long (errno = 90)
```

**To Reproduce**
1. Enable syslog from windows to an RFC5424 capable receiver
2. run tcpdump on the receiver
3. edit the pcap to modify source->dest ip's and macs
4. run `tcpreplay --loop=0 --intf1=ens18 myfile.pcap`

**Expected behavior**
All events (including the long ones) should show up in my log receiver

**System (please complete the following information):**
 - OS: Ubuntu
 - OS version: 18.04 and 20.04 (tested on 2 systems)
 - Tcpreplay Version 4.3.2

**Comment by lroolle** [comment]
Set a larger mtu for related eth works for me:
```sh
ifconfig eth0 mtu 9216
```

**Comment by fklassen** [comment]
This is expected behaviour. If the packet being sent is larger than the egress interface MTU, libpcap generates this error.

**Comment by fcp999** [comment]
Might I suggest 
tcprewrite  --mtu=8000 --mtu-trunc --skip-soft-errors  -i broken.pcap -o fixed.pcap
