### ISSUE TITLE
[Bug] Tests failed

### ISSUE THREAD

**Issue by ikreb7** [appneta/tcpreplay#681]
Hello Fred,

thank your very much for your project.

I want to install tcpreplay like at your video. But I get few errors if I run the tests. Do you have any ideas what could be the problem? 

Of course I can give you even more information if wished.

**To Reproduce**
1. apt install build-essential libpcap-dev
2. wget https://github.com/appneta/tcpreplay/releases/download/v4.3.4/tcpreplay-4.3.4.tar.xz
3. tar xf tcpreplay-4.3.4.tar.xz
4. ./configure
5. make
6. sudo make test

[tcpreplay] Basic test: make[1]: *** [Makefile:796: replay_basic] Fehler 255
[tcpreplay] Cache test: make[1]: *** [Makefile:802: replay_cache] Fehler 255
[tcpreplay] Packets/sec test: make[1]: *** [Makefile:1034: replay_pps] Fehler 255
[tcpreplay] Mbps test: make[1]: *** [Makefile:1040: replay_rate] Fehler 255
[tcpreplay] Topspeed test: make[1]: *** [Makefile:1058: replay_top] Fehler 255
[tcpreplay] Config file/VLAN add test: make[1]: *** [Makefile:1076: replay_config] Fehler 255
[tcpreplay] Multiplier test: make[1]: *** [Makefile:1046: replay_multi] Fehler 255
[tcpreplay] Packets/sec Multiplier test: make[1]: *** [Makefile:1052: replay_pps_multi] Fehler 255
[tcpreplay] Precache test: make[1]: *** [Makefile:1064: replay_precache] Fehler 255
[tcpreplay] Statistics test: make[1]: *** [Makefile:814: replay_stats] Fehler 255
[tcpreplay] Dual file test: make[1]: *** [Makefile:1082: replay_dualfile] Fehler 255
[tcpreplay] Maximum sleep test: make[1]: *** [Makefile:1088: replay_maxsleep] Fehler 255

**System:**
 - OS: Ubuntu
 - OS 18.04 and 20.04
 - Tcpreplay Version: 4.3.4

**Comment by fklassen** [comment]
It appears that this issue exists with 4.3.3-2 and may be related to autoconf 2.70. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978905

**Comment by fklassen** [comment]
Updated tests as part of Bug #677. Please reopen issue if it recurs in 4.4.0 (once released).
