### ISSUE TITLE
[Bug] Not able to read from STDIN

### ISSUE THREAD

**Issue by jboullianne** [appneta/tcpreplay#708]
**Describe the bug**
Not able to read from STDIN in tcpreplay 4.4.0. When trying to pass the `-` as the file descriptor for reading from STDIN, the program outputs:
`Fatal Error: Unable to retrieve informations from file -: No such file or directory`

This previously worked when running version 4.3.4.

**To Reproduce**
1. `sudo yum instal tcpreplay`
2. `sudo tcpreplay -i <interface_name> -`

**Expected behavior**
Expected tcpreplay to read in packet data from STDIN

**System (please complete the following information):**
 - OS: Centos Stream 8
 - Tcpreplay Version 4.4.0

**Comment by fklassen** [comment]
Fixed in PR #709
