### ISSUE TITLE
MacOS Build Busted

### ISSUE THREAD

**Issue by bpalmer7440** [appneta/tcpreplay#745]
When building from appneta-tcpreplay-v4.4.1-1-g09f0774.tar.gz on macOS Monterey 12.0.1 I get the following error when trying to generate configure:
%$ ./autogen.sh
autoheader: error: error: AC_CONFIG_HEADERS not found in configure.ac

**To Reproduce**
1. download appneta-tcpreplay-v4.4.1-1-g09f0774.tar.gz from http://tcpreplay.appneta.com/wiki/installation.html#downloads <master tarball link> onto a system with MacOS Monterey 12.0.1
2. %$ tar -xvzf appneta-tcpreplay-v4.4.1-1-g09f0774.tar.gz
3. %$ cd appneta-tcpreplay-09f0774
4. %$ ./autogen.sh
autoheader: error: error: AC_CONFIG_HEADERS not found in configure.ac

**I expect to get a message similar to the one I get on my Ubuntu 18.04.05 VM:**
\~/appneta-tcpreplay-09f0774$ ./autogen.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:169: installing 'config/ar-lib'
configure.ac:169: installing 'config/compile'
configure.ac:30: installing 'config/config.guess'
configure.ac:30: installing 'config/config.sub'
configure.ac:165: installing 'config/install-sh'
configure.ac:165: installing 'config/missing'
lib/Makefile.am: installing 'config/depcomp'

**System (please complete the following information):**
 - OS: macOS
 - OS version: Monterey 12.0.1
 - Tcpreplay Version [e.g. 4.3.2] 4.4.1 (as evidenced by Ubuntu build from same tarball)

**Additional context**

autoheader --version -> 2.71
autoconf --version -> 2.7.1
aclocal --version -> 1.16.5
autogen --version -> 5.18.16

**Comment by fklassen** [comment]
As per instructions on download page, just run ...

```
./configure
make
sudo make install
```

The `autogen.sh` is for build machines that have many prereq libraries and tools installed. It generates the `configure` script. For distributions, the `configure` script is already generated, so there is no need to run `autogen.sh`.

**Comment by bpalmer7440** [comment]
There is no configure script included in the latest release. It is missing.

**Comment by fklassen** [comment]
reopening - will remove autogen.sh from distribution tarball

**Comment by fklassen** [comment]
Fixed in PR #747
