### ISSUE TITLE
Unable to process unsupported DLT type : 802.11 plus radiotap header (0x7f)

### ISSUE THREAD

**Issue by Anilpmeasure** [appneta/tcpreplay#777]
Dear Team,

    I am trying to replay the packets using tcpreplay tool and getting an error as "Unable to process unsupported DLT type : 802.11 plus radiotap header (0x7f). the pcap file being used was captured by wifi interface and it has 802,11 radiotap header. Please do help resolve this problem. thanks

**Comment by fklassen** [comment]
Use [DLT_IEEE802_11_RADIO](https://github.com/appneta/tcpreplay/blob/7cf630d9c30648d23182ea51e019867a67afb076/src/common/dlt_names.h#L242) not [DLT_IEE80211.](https://github.com/appneta/tcpreplay/blob/7cf630d9c30648d23182ea51e019867a67afb076/src/common/dlt_names.h#L170) Also, next time file in a bug report

**Comment by paulorb** [comment]
@fklassen  I am having the same issue, when you say use the DLT_IEEE802_11_RADIO what do you mean?

`Fatal Error: Unable to process unsupported DLT type: 802.11 plus radiotap header (0x7f)`

**Comment by fklassen** [comment]
> [@fklassen](https://github.com/fklassen) I am having the same issue, when you say use the DLT_IEEE802_11_RADIO what do you mean?
> 
> `Fatal Error: Unable to process unsupported DLT type: 802.11 plus radiotap header (0x7f)`

We support PCAP files that are DLT_IEEE802_11_RADIO. If you want support for other DLT types, open a new issue and select the template feature. Don't forget to add sample PCAP file(s). To do so, I suggest renaming them to `xxx.pcap.txt` so GitHub will accept them.
