### ISSUE TITLE
[Bug] tcpreplay goes full speed after some time

### ISSUE THREAD

**Issue by mikolajpod** [appneta/tcpreplay#779]
Hi.

I'm using the following command
**tcpreplay -i ens224 -p 4800 -l 0 file.pcap**
and at the begining the rate is as expected.

**After some time (12-13 days) it starts to replay at full speed.**

After stopping with ctrl-c (about 12 hours after going wild) it printed:
Actual: 22192758064 packets (30315118877440 bytes) sent in 1113425.57 seconds
Rated: 27226892.9 Bps, 217.81 Mbps, 19931.96 pps
Flows: 2 flows, 0.00 fps, 1710129550895712 flow packets, 0 non-flow
Statistics for network device: ens224
        Successful packets:        22192758063
        Failed packets:            0
        Truncated packets:         0
        Retried packets (ENOBUFS): 0
        Retried packets (EAGAIN):  0

**TCPREPLAY VERSION:**
tcpreplay version: 4.3.3 (build git:v4.3.3) (debug)
Copyright 2013-2018 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.10.0
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Injection method: PF_PACKET send()
Not compiled with netmap

**OS INFO:**
uname -a
Linux sycope-os 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
(It's debian 11.1)

**HARDWARE:**
lspci
...
0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)
13:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)

**Comment by fklassen** [comment]
This requires moving from 32 to 64 byte counters which is more of a feature than a bug. Too much for 4.4.4.

**Comment by fklassen** [comment]
Fixed in PR #821
