### ISSUE TITLE
[Bug] Rewriting Linux Cooked capture layer with --dlt=enet breaks the output PCAP format

### ISSUE THREAD

**Issue by msi3na** [appneta/tcpreplay#790]
I am trying to rewrite PCAPs with Linux Cooked Capture, the output format is malformed and can't be properly read by wireshark.

Command
tcprewrite --dlt=enet -i pcap.pcap -o pcap1.pcap

PCAPs
[Archive.zip](https://github.com/appneta/tcpreplay/files/10880377/Archive.zip)

Tried on both versions below:

-- MAC OS homebrew
tcprewrite version: 4.4.3 (build git:v4.4.3)
Copyright 2013-2022 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.14
Compiled against libpcap: 1.10.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: enabled

-- Ubuntu 20.4 LTS
tcprewrite version: 4.4.1 (build git:v4.4.1)
Copyright 2013-2022 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.9.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: disabled

**Comment by msi3na** [comment]
![image](https://user-images.githubusercontent.com/92431617/222681965-73521dd7-7a7a-49ec-a794-387894ee32ab.png)

**Comment by hoxnox** [comment]
same for me
```
tcprewrite -i 1.pcap -o 1_.pcap --dlt=enet
```
[1.pcap.gz](https://github.com/appneta/tcpreplay/files/11104062/1.pcap.gz)

**Comment by fklassen** [comment]
closing as dup of #792
