### ISSUE TITLE
[Bug] VLAN deletion option --enet-vlan=del does not work with Linux Cooked Capture

### ISSUE THREAD

**Issue by msi3na** [appneta/tcpreplay#791]
I am trying to delete the VLAN layer from PCAPs with Linux Cooked Capture. 
It seems ineffective: input and output PCAPs are the same. 
The option works well with PCAPs having regular VLAN tags over Ethernet.

Command
tcprewrite --enet-vlan=del -i pcap_vlan.pcap -o pcap_vlan1.pcap

Attached input and output file
[Archive 2.zip](https://github.com/appneta/tcpreplay/files/10880446/Archive.2.zip)

Tried on both versions below:

-- MAC OS homebrew
tcprewrite version: 4.4.3 (build git:v4.4.3)
Copyright 2013-2022 by Fred Klassen - AppNeta
Copyright 2000-2012 by Aaron Turner
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.14
Compiled against libpcap: 1.10.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: enabled

-- Ubuntu 20.4 LTS
tcprewrite version: 4.4.1 (build git:v4.4.1)
Copyright 2013-2022 by Fred Klassen - AppNeta
Copyright 2000-2012 by Aaron Turner
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.9.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: disabled

![image](https://user-images.githubusercontent.com/92431617/222682953-c4ba827a-d7d5-4d7f-b721-fbb067e4e87e.png)

**Comment by fklassen** [comment]
Even though this looks quite a bit like Ethernet packets, SLL is just enough different that it needs a major implementation. For now, packet edits are not supported for SLL and SLL2. This is enhancement is shelved for the forseeable future.
