### ISSUE TITLE
DLT plugin not available

### ISSUE THREAD

**Issue by vij-vf** [appneta/tcpreplay#798]
Hi,

I'm new to tcprewrite usage. I tried to rewrite SLL to ETHERNET but getting an error that source plugin not available.
Attached screenshot.
<img width="953" alt="tes_op" src="https://github.com/appneta/tcpreplay/assets/83247068/5678af2c-c185-4677-92ed-12b4fc99d3ef">
<img width="644" alt="tcprewrite_ver" src="https://github.com/appneta/tcpreplay/assets/83247068/d4596f88-79a2-4b48-9d8b-f588e6474f78">

**Comment by fklassen** [comment]
Closing as dup of #792
