### ISSUE TITLE
[Bug] Issue with No DLT plugin available for source !

### ISSUE THREAD

**Issue by breizho** [appneta/tcpreplay#799]
Hello,

This is my tcprewrite issue:

tcprewrite -v -i dump_XX.pcap -o ano_dump_XXpcap 

Fatal Error: Error initializing tcpedit: From plugins/dlt_plugins.c:tcpedit_dlt_init() line 148:
**No DLT plugin available for source DLT: 0x6d**

- This capture was made with tcpdump : tcpdump -vvv -s0 -w /log/dump_XX.pcap -nXi enc0 host

- When I open wireshark tool to read format of capture, I can read:
> Encapsulation type : MIME (134)
> Protocols in fram: mime_dlt:file-pcap
> PCAP FILE FORMAT > >HEADER > Link Type: ENC (109)

Can you help me please ?

Tks 

Breizho

tcprewrite version: 4.4.3 (build git:v4.4.3)
under CentOS

**Comment by fklassen** [comment]
Not a bug. Link Type 109 is not supported.

What type of interface is enc0? Doesn't appear to be anything common.

Attach pcap file and I'll have a look.

**Comment by fklassen** [comment]
No response ... closing. If reopening fill in bug report form with all fields included.
