### ISSUE TITLE
Does not compile PF_RING DNA version of libpcap

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#81]
As per Luca Deri, the patch below should allow wire-rate TX with PF_RING DNA via the following sample command:

```
configure --with-libpcap=3D$HOME/PF_RING/userland/libpcap-1.1.1-ring
```

```
deri@iMacLuca 183> diff configure.ac ~/tcpreplay-4.0.3/configure.ac=20
290a291,294
> dnl Force libpcap usage
> force_pcap=3Dno
> AC_ARG_ENABLE(force_pcap, AC_HELP_STRING([--enable-force_pcap], [Force li=
bpcap usage]))
>=20
376a381
>     force_pcap=3Dyes
858a864
> if test "${force_pcap}" =3D "no"; then :
946a953,954
> fi
> =
```

**Comment by nickwallen** [comment]
Are up-to-date instructions documented anywhere else besides this issue?  I have been looking, but have not found any.

**Comment by fklassen** [comment]
No need to document different flavors of`libpcap`. PF_RING implemented in libpcap makes its use transparent.

Help for the `./configure --with-libpcap=` is available with `./configure -h`

**Comment by nickwallen** [comment]
Many thanks @fklassen.  I opened #395 with a more detailed question on this topic.

**Comment by nickwallen** [comment]
@fklassen Even if the documentation says something to that effect, it would be helpful to users.
