### ISSUE TITLE
[Bug] tcpreplay-edit recomputes IPv4 checksums unnecessarily

### ISSUE THREAD

**Issue by green-nsk** [appneta/tcpreplay#815]
**Describe the bug**

I think [this line](https://github.com/appneta/tcpreplay/blob/43693c4a92dda227a5134ae5e71a7247ae345323/src/tcpedit/tcpedit.c#L321) causes tcpreplay-edit to recompute all checksums for all IP packets unnecessarily. I noticed this because of a [problem with recomputing UDP checksums](https://github.com/appneta/tcpreplay/pull/814), but in general I think it is 1) not allowing users to replay pcaps with errors 2) waste of time.

**To Reproduce**

Replay any pcap with errors in IP/UDP/TCP header checksums.

**Expected behavior**

I expect checksums to stay intact unless explicitly requested

**Screenshots**

N/A

**System (please complete the following information):**
All

**Additional context**

I tried fixing it, but seemingly unrelated tests keep breaking, so I figured I'm in over my head.

**Comment by fklassen** [comment]
Fixed in PR #846
