### ISSUE TITLE
[Bug] Possible bug on tcprewrite version 4.4.4 for Ethernet layer

### ISSUE THREAD

**Issue by kYroL01** [appneta/tcpreplay#826]
**Describe the bug**
With `tcprewrite` version **4.4.4** I could not change the _Linux cooked capture_ layer (SLL) to Ethernet layer, while it's working fine with version **4.3.1**

**To Reproduce**
1. Take a pcap with Linux cooked capture (DLT_LINUX_SLL 113)
2. Run the command `tcprewrite --dlt=enet --enet-dmac=12:ab:34:89:fb:10 --enet-smac=00:1e:79:9e:f8:00 -i old.pcap -o new.pcap`
3. Open the `new.pcap` with wireshark and you don't see the layers detected correctly

**Screenshots**
Version **4.4.4**
![ScreenShot_20230918155304](https://github.com/appneta/tcpreplay/assets/7222956/47b2d15c-183a-46d3-89ca-8c6d80ce1b78)

Version **4.3.1**
![ScreenShot_20230918155554](https://github.com/appneta/tcpreplay/assets/7222956/c3726d05-e1b7-4369-87dc-7c64cc395760)

**System (please complete the following information):**
 - OS: Debian 11
 - Tcprewrite Version [e.g. 4.4.4]

**Comment by fklassen** [comment]
This issue was solved in PR #873 as part of fix for bug #792.

**Comment by kYroL01** [comment]
Thank you!!
