### ISSUE TITLE
[Bug] Packets slowly drift further and further randomly when played or sent using tcpreplay

### ISSUE THREAD

**Issue by anoopcc99** [appneta/tcpreplay#829]
**Describe the bug**
take a time sensitive pcap file and send it interface using tcpreplay, the captured packets at the other end of interface seen does not honor the packet interval time difference, instead varies randomly.
transmit pcap file:
![image](https://github.com/appneta/tcpreplay/assets/46996046/1edd243a-adb6-44c4-be7d-03562bdb016e)

Captured pcap file:
![image](https://github.com/appneta/tcpreplay/assets/46996046/634b182a-d8e0-4cfe-b0de-c8fc56816fbd)

Time Drift:
![Picture1](https://github.com/appneta/tcpreplay/assets/46996046/4a2813d0-49df-45de-94cc-1978de55e70d)

**To Reproduce**
1. take any timestamp based pcap file
2. send the pcap file using tcpreplay to the interface
3. capture the incoming packets on other end on interface
4. note the time drift

**Expected behavior**
I would expect the time drift to be constant or minimum. 

**System (please complete the following information):**
 - OS: "Ubuntu 22.04 LTS"
 - OS version: "22.04 LTS (Jammy Jellyfish)"
 - TcpReplay Version: 4.3.4

**Comment by Weissle** [comment]
Met this issue before.
When we replay with the origin speed, tcpreplay sleeps according to the time gap between two package.
However, the overhead like sending package and waking up thread are ignored. These overheads are accumulated little by little which lead to the drift.
relative code is here. https://github.com/appneta/tcpreplay/blob/43693c4a92dda227a5134ae5e71a7247ae345323/src/send_packets.c#L468C23-L468C23

**Comment by fklassen** [comment]
I think the graph is pretty good. Much of what you are seeing is the delay from when the packet was sent until it was copied and recorded for packet capture. Usually I expect around 200-400 usec before it leaves a NIC card, so I am pretty happy with this. I am especially impressed by the fact that it levels off after a just a few packets.

What hardware are you using? Is this a VM or docker? I expect that this is pretty good hardware if the results are this good.

I will close as not-a-bug.
