### ISSUE TITLE
Warning: Unable to process unsupported DLT type: Ethernet (0x1)

### ISSUE THREAD

**Issue by KatherineJXY** [appneta/tcpreplay#835]
I was trying to replay the packets using the tcpreplay tool and got an error: "Warning: Unable to process unsupported DLT type: Ethernet (0x1)."
tcpreplay version: 4.4.3
Pcap file: https://pages.cs.wisc.edu/~tbenson/IMC_DATA/univ1_trace.tgz
Any clues?

**Comment by fklassen** [comment]
Your captures are full of malformed packets. Tcpreplay is simply dropping the invalid ones.
<img width="1594" alt="image" src="https://github.com/appneta/tcpreplay/assets/1899327/4a07d6b4-0349-403c-9d8a-99a8363e14a2">

**Comment by fklassen** [comment]
After more review, determined that some EtherType I packets are wrongly flagged as as bad. For example, packet #114 in `test.pcap`.

**Comment by fklassen** [comment]
Fixed in PR #880
